// Importação COMPLETA - SEM coluna category
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://onzdkpqtzfxzcdyxczkn.supabase.co';
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uemRrcHF0emZ4emNkeXhjemtuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODMwMDM3NCwiZXhwIjoyMDgzODc2Mzc0fQ.KGVOkPLra7-EBr6MewnZJa2Kxg6lyxuJWKh-dw9Riu4';

const supabase = createClient(supabaseUrl, supabaseServiceKey);

console.log("🚀 IMPORTAÇÃO COMPLETA - 554 ALIMENTOS\n");

const foodDecomposition = {
  en: [
    { name: "5-hour energy", ingredients: ["cafeína", "vitaminas do complexo b"] },
    { name: "À milanesa", ingredients: ["trigo", "ovo", "farinha de rosca", "óleo"] },
    { name: "A2 milk", ingredients: ["leite"] },
    { name: "Achocolatado", ingredients: ["cacau", "açúcar", "leite"] },
    { name: "Açúcar de confeiteiro", ingredients: ["açúcar", "amido de milho"] },
    { name: "Aged cheese", ingredients: ["leite", "coalho", "sal"] },
    { name: "Agridoce", ingredients: ["açúcar", "vinagre", "tomate"] },
    { name: "Aioli", ingredients: ["alho", "ovo", "azeite"] },
    { name: "Alho frito", ingredients: ["alho", "óleo"] },
    { name: "Almond butter", ingredients: ["amêndoa"] },
    { name: "Almond milk", ingredients: ["amêndoa", "água"] },
    { name: "Almôndega de soja", ingredients: ["proteína de soja", "cebola", "alho"] },
    { name: "American cheese", ingredients: ["leite", "soro de leite", "emulsificantes"] },
    { name: "Amp energy", ingredients: ["cafeína", "taurina", "açúcar"] },
    { name: "Arepa", ingredients: ["farinha de milho", "água", "sal"] },
    { name: "Baba ghanoush", ingredients: ["berinjela", "tahine", "alho", "azeite", "limão"] },
    { name: "Bagel", ingredients: ["trigo", "fermento"] },
    { name: "Bagels", ingredients: ["farinha de trigo", "fermento", "sal", "malte"] },
    { name: "Baklava", ingredients: ["massa filo", "nozes", "pistache", "mel", "manteiga"] },
    { name: "Banana bread", ingredients: ["banana", "trigo", "açúcar", "ovo"] },
    { name: "Bang energy", ingredients: ["cafeína", "aminoácidos"] },
    { name: "Barbecue", ingredients: ["tomate", "açúcar", "vinagre", "especiarias"] },
    { name: "Beer", ingredients: ["cevada", "malte", "lúpulo", "fermento"] },
    { name: "Beignet", ingredients: ["trigo", "ovo", "leite", "açúcar"] },
    { name: "Bhaji", ingredients: ["cebola", "grão de bico", "especiarias"] },
    { name: "Biryani", ingredients: ["arroz", "especiarias", "carne"] },
    { name: "Biscoito", ingredients: ["trigo", "açúcar", "manteiga"] },
    { name: "Blue cheese", ingredients: ["leite", "penicillium", "sal"] },
    { name: "Boiled eggs", ingredients: ["ovo"] },
    { name: "Brioche", ingredients: ["trigo", "manteiga", "ovo", "açúcar"] },
    { name: "Brownie", ingredients: ["chocolate", "manteiga", "açúcar", "ovo", "trigo"] },
    { name: "Buñuelo", ingredients: ["trigo", "ovo", "açúcar"] },
    { name: "Burrito", ingredients: ["trigo", "feijão", "arroz", "carne"] },
    { name: "Buttercream", ingredients: ["manteiga", "açúcar"] },
    { name: "Butterfinger", ingredients: ["amendoim", "chocolate", "açúcar"] },
    { name: "Buttermilk", ingredients: ["leite", "bactérias lácticas"] },
    { name: "Caffeinated candy", ingredients: ["açúcar", "cafeína"] },
    { name: "Caffeinated gum", ingredients: ["cafeína", "goma base", "açúcar"] },
    { name: "Caffeinated mints", ingredients: ["cafeína", "açúcar", "menta"] },
    { name: "Candy", ingredients: ["açúcar", "xarope de milho"] },
    { name: "Canned fruit in syrup", ingredients: ["fruta", "açúcar", "água"] },
    { name: "Cannoli", ingredients: ["trigo", "ricota", "açúcar", "chocolate"] },
    { name: "Cappelletti", ingredients: ["trigo", "ovo", "carne"] },
    { name: "Cappuccino", ingredients: ["café", "leite", "espuma de leite"] },
    { name: "Carpaccio", ingredients: ["carne crua", "azeite", "limão"] },
    { name: "Carrot cake", ingredients: ["cenoura", "trigo", "açúcar", "ovo", "nozes"] },
    { name: "Cashew butter", ingredients: ["castanha de caju"] },
    { name: "Cashew cheese", ingredients: ["castanha de caju", "fermento nutricional"] },
    { name: "Cashew milk", ingredients: ["castanha de caju", "água"] },
    { name: "Cereal", ingredients: ["milho", "trigo", "açúcar"] },
    { name: "Ceviche", ingredients: ["peixe", "limão", "cebola"] },
    { name: "Challah", ingredients: ["trigo", "ovo", "mel"] },
    { name: "Challah bread", ingredients: ["farinha de trigo", "ovo", "açúcar", "fermento"] },
    { name: "Chapati", ingredients: ["farinha de trigo integral", "água", "óleo"] },
    { name: "Charlotte", ingredients: ["biscoito", "creme", "frutas"] },
    { name: "Cheddar cheese", ingredients: ["leite", "coalho", "sal"] },
    { name: "Cheesecake", ingredients: ["cream cheese", "açúcar", "ovo", "biscoito"] },
    { name: "Chimichanga", ingredients: ["tortilha", "carne", "feijão", "queijo"] },
    { name: "Chimichurri", ingredients: ["salsa", "alho", "orégano", "vinagre", "azeite"] },
    { name: "Chocolate", ingredients: ["cacau", "açúcar", "leite"] },
    { name: "Churro", ingredients: ["trigo", "açúcar", "óleo"] },
    { name: "Chutney", ingredients: ["frutas", "especiarias", "açúcar"] },
    { name: "Coca-cola", ingredients: ["cafeína", "açúcar", "ácido fosfórico"] },
    { name: "Coca-cola zero", ingredients: ["cafeína", "aspartame", "ácido fosfórico"] },
    { name: "Condensed milk", ingredients: ["leite", "açúcar"] },
    { name: "Cookie", ingredients: ["trigo", "manteiga", "açúcar", "ovo", "chocolate"] },
    { name: "Crackers", ingredients: ["farinha de trigo", "óleo", "sal"] },
    { name: "Crème brûlée", ingredients: ["creme de leite", "ovo", "açúcar", "baunilha"] },
    { name: "Crostini", ingredients: ["pão", "azeite"] },
    { name: "Cupcake", ingredients: ["trigo", "ovo", "açúcar", "manteiga"] },
    { name: "Curry", ingredients: ["especiarias", "leite de coco"] },
    { name: "Dal", ingredients: ["lentilha", "especiarias"] },
    { name: "Donut", ingredients: ["trigo", "açúcar", "ovo", "leite"] },
    { name: "Dosa", ingredients: ["arroz", "lentilha"] },
    { name: "Dulce de leche", ingredients: ["leite", "açúcar"] },
    { name: "Éclair", ingredients: ["trigo", "ovo", "manteiga", "creme", "chocolate"] },
    { name: "Edamame", ingredients: ["soja"] },
    { name: "Empanada", ingredients: ["trigo", "carne"] },
    { name: "Enchilada", ingredients: ["milho", "carne", "queijo", "molho"] },
    { name: "Energy drinks", ingredients: ["cafeína", "taurina", "açúcar"] },
    { name: "Energy shots", ingredients: ["cafeína", "vitaminas"] },
    { name: "Evaporated milk", ingredients: ["leite"] },
    { name: "Fajita", ingredients: ["carne", "pimentão", "cebola", "tortilha"] },
    { name: "Falafel", ingredients: ["grão de bico", "especiarias"] },
    { name: "Fermented soy products", ingredients: ["soja fermentada", "sal"] },
    { name: "Fettuccine", ingredients: ["trigo", "ovo"] },
    { name: "Flan", ingredients: ["leite", "ovo", "açúcar"] },
    { name: "Flavored yogurt", ingredients: ["leite", "açúcar", "aromatizante"] },
    { name: "Fondant", ingredients: ["açúcar", "glucose"] },
    { name: "French toast", ingredients: ["pão", "leite", "ovo", "açúcar", "canela"] },
    { name: "Fruit preserves", ingredients: ["frutas", "açúcar", "sulfito"] },
    { name: "Fruit roll-ups", ingredients: ["fruta", "açúcar", "xarope de milho"] },
    { name: "Fruit-flavored yogurt", ingredients: ["leite", "fruta", "açúcar"] },
    { name: "Ganache", ingredients: ["chocolate", "creme de leite"] },
    { name: "Gelato", ingredients: ["leite", "açúcar", "ovo"] },
    { name: "Gianduja", ingredients: ["avelã", "chocolate", "açúcar"] },
    { name: "Gnocchi", ingredients: ["batata", "farinha de trigo", "ovo"] },
    { name: "Groundnut butter", ingredients: ["amendoim"] },
    { name: "Gyoza", ingredients: ["trigo", "carne", "repolho"] },
    { name: "Hamburger", ingredients: ["carne bovina", "sal", "gordura"] },
    { name: "Hummus", ingredients: ["grão de bico", "tahine", "limão", "alho"] },
    { name: "Ice cream", ingredients: ["leite", "açúcar", "creme de leite"] },
    { name: "Idli", ingredients: ["arroz", "lentilha"] },
    { name: "Kebab", ingredients: ["carne", "especiarias"] },
    { name: "Korma", ingredients: ["creme", "castanha", "especiarias"] },
    { name: "Lasagna", ingredients: ["trigo", "ovo", "queijo", "leite", "carne"] },
    { name: "Lupin bread", ingredients: ["farinha de tremoço", "farinha de trigo", "fermento"] },
    { name: "Lupin crackers", ingredients: ["farinha de tremoço", "farinha de trigo"] },
    { name: "Lupin milk", ingredients: ["tremoço", "água"] },
    { name: "Lupin pasta", ingredients: ["farinha de tremoço", "farinha de trigo"] },
    { name: "Macaron", ingredients: ["amêndoa", "açúcar", "clara de ovo"] },
    { name: "Malasada", ingredients: ["trigo", "ovo", "açúcar", "leite"] },
    { name: "Malted milk", ingredients: ["leite", "malte de cevada"] },
    { name: "Marzipan", ingredients: ["amêndoa", "açúcar"] },
    { name: "Massaman", ingredients: ["especiarias", "leite de coco", "amendoim"] },
    { name: "Merengue", ingredients: ["clara de ovo", "açúcar"] },
    { name: "Milk shake", ingredients: ["leite", "sorvete", "açúcar"] },
    { name: "Mixed nuts", ingredients: ["amêndoa", "castanha de caju", "noz", "avelã", "macadâmia"] },
    { name: "Mocha", ingredients: ["café", "chocolate", "leite"] },
    { name: "Monster energy", ingredients: ["cafeína", "taurina", "açúcar"] },
    { name: "Muffin", ingredients: ["trigo", "ovo", "açúcar", "manteiga"] },
    { name: "Naan", ingredients: ["trigo", "iogurte", "fermento"] },
    { name: "Nachos", ingredients: ["milho", "queijo"] },
    { name: "Nos energy drink", ingredients: ["cafeína", "taurina", "açúcar"] },
    { name: "Nougat", ingredients: ["amêndoa", "mel", "clara de ovo"] },
    { name: "Nuggets", ingredients: ["frango", "trigo"] },
    { name: "Nut-flavored", ingredients: ["castanhas", "aromatizante"] },
    { name: "Pad thai", ingredients: ["macarrão de arroz", "amendoim", "ovo", "camarão"] },
    { name: "Pakora", ingredients: ["grão de bico", "legumes"] },
    { name: "Palak", ingredients: ["espinafre", "especiarias"] },
    { name: "Palmier", ingredients: ["trigo", "manteiga", "açúcar"] },
    { name: "Pancakes", ingredients: ["trigo", "ovo", "leite"] },
    { name: "Paneer", ingredients: ["leite", "coalho"] },
    { name: "Panna cotta", ingredients: ["creme de leite", "açúcar", "gelatina"] },
    { name: "Papadum", ingredients: ["farinha de lentilha", "óleo", "sal"] },
    { name: "Parfait", ingredients: ["iogurte", "granola", "frutas"] },
    { name: "Pasta", ingredients: ["trigo", "ovo"] },
    { name: "Pavlova", ingredients: ["clara de ovo", "açúcar", "creme", "frutas"] },
    { name: "Peanut butter", ingredients: ["amendoim"] },
    { name: "Penne", ingredients: ["trigo"] },
    { name: "Pepsi", ingredients: ["cafeína", "açúcar", "ácido fosfórico"] },
    { name: "Pepsi max", ingredients: ["cafeína", "aspartame"] },
    { name: "Pesto", ingredients: ["manjericão", "pinhão", "parmesão", "azeite", "alho"] },
    { name: "Pizza", ingredients: ["trigo", "fermento", "queijo", "tomate", "azeite"] },
    { name: "Poke", ingredients: ["peixe", "arroz", "alga"] },
    { name: "Pound cake", ingredients: ["trigo", "manteiga", "açúcar", "ovo"] },
    { name: "Praline", ingredients: ["amêndoa", "açúcar"] },
    { name: "Prawn crackers", ingredients: ["camarão", "amido de tapioca"] },
    { name: "Pre-workout supplements", ingredients: ["cafeína", "beta-alanina", "creatina"] },
    { name: "Pretzel", ingredients: ["trigo", "fermento", "sal"] },
    { name: "Profiterole", ingredients: ["trigo", "ovo", "manteiga", "creme"] },
    { name: "Pumpernickel bread", ingredients: ["farinha de centeio", "farinha de trigo", "fermento"] },
    { name: "Pupusa", ingredients: ["milho", "queijo", "feijão"] },
    { name: "Quesadilla", ingredients: ["trigo", "queijo"] },
    { name: "Raita", ingredients: ["iogurte", "pepino", "especiarias"] },
    { name: "Ramen", ingredients: ["trigo", "ovo", "carne", "shoyu"] },
    { name: "Red bull", ingredients: ["cafeína", "taurina", "açúcar"] },
    { name: "Red velvet", ingredients: ["trigo", "cacau", "ovo", "cream cheese"] },
    { name: "Ricotta cheese", ingredients: ["soro de leite", "leite"] },
    { name: "Rockstar energy", ingredients: ["cafeína", "taurina", "açúcar"] },
    { name: "Roux", ingredients: ["farinha de trigo", "manteiga"] },
    { name: "Rye bread", ingredients: ["farinha de centeio", "farinha de trigo", "fermento"] },
    { name: "Sabayon", ingredients: ["ovo", "açúcar", "vinho"] },
    { name: "Samosa", ingredients: ["trigo", "batata", "ervilha", "especiarias"] },
    { name: "Scrambled eggs", ingredients: ["ovo", "leite", "manteiga"] },
    { name: "Seafood flavoring", ingredients: ["extrato de peixe", "extrato de crustáceos"] },
    { name: "Seafood sticks", ingredients: ["peixe", "amido", "clara de ovo"] },
    { name: "Seafood stock", ingredients: ["peixe", "crustáceos", "sal"] },
    { name: "Sesame bagel", ingredients: ["farinha de trigo", "gergelim", "fermento"] },
    { name: "Sesame bread", ingredients: ["farinha de trigo", "gergelim", "fermento"] },
    { name: "Sesame crackers", ingredients: ["farinha de trigo", "gergelim"] },
    { name: "Sfogliatella", ingredients: ["trigo", "ricota", "laranja"] },
    { name: "Shawarma", ingredients: ["carne", "pão pita", "especiarias"] },
    { name: "Shortcake", ingredients: ["trigo", "manteiga", "açúcar", "creme", "morango"] },
    { name: "Shoyu", ingredients: ["soja", "trigo", "sal"] },
    { name: "Smoothie", ingredients: ["fruta", "iogurte", "leite"] },
    { name: "Soft cheeses", ingredients: ["leite", "coalho", "creme"] },
    { name: "Sopapilla", ingredients: ["trigo", "fermento", "mel"] },
    { name: "Sourdough bread", ingredients: ["farinha de trigo", "fermento", "sal"] },
    { name: "Soy cheese", ingredients: ["soja", "óleo vegetal"] },
    { name: "Soy milk", ingredients: ["soja", "água"] },
    { name: "Soy yogurt", ingredients: ["leite de soja", "culturas"] },
    { name: "Spring roll", ingredients: ["arroz", "legumes"] },
    { name: "Strudel", ingredients: ["trigo", "maçã", "açúcar", "canela"] },
    { name: "Sushi", ingredients: ["arroz", "peixe", "alga"] },
    { name: "Sweetened beverages", ingredients: ["água", "açúcar"] },
    { name: "Sweetened condensed milk", ingredients: ["leite", "açúcar"] },
    { name: "Sweetened yogurt", ingredients: ["leite", "açúcar", "culturas"] },
    { name: "Swiss cheese", ingredients: ["leite", "coalho", "sal"] },
    { name: "Taco", ingredients: ["milho", "carne", "queijo"] },
    { name: "Tamale", ingredients: ["milho", "carne", "especiarias"] },
    { name: "Tandoori", ingredients: ["iogurte", "especiarias"] },
    { name: "Tartar", ingredients: ["maionese", "pepino", "alcaparra"] },
    { name: "Tartare", ingredients: ["carne crua", "alcaparra", "cebola"] },
    { name: "Temaki", ingredients: ["arroz", "peixe", "alga"] },
    { name: "Teriyaki", ingredients: ["shoyu", "açúcar", "mirin", "gengibre"] },
    { name: "Tikka masala", ingredients: ["tomate", "creme", "especiarias"] },
    { name: "Tiramisu", ingredients: ["mascarpone", "café", "ovo", "biscoito", "cacau"] },
    { name: "Tortellini", ingredients: ["farinha de trigo", "ovo", "recheio"] },
    { name: "Trifle", ingredients: ["bolo", "creme", "frutas"] },
    { name: "Vindaloo", ingredients: ["carne", "vinagre", "especiarias"] },
    { name: "Vodka", ingredients: ["trigo", "batata"] },
    { name: "Wafer", ingredients: ["farinha de trigo", "açúcar", "gordura vegetal"] },
    { name: "Waffle", ingredients: ["trigo", "ovo", "leite", "manteiga", "açúcar"] },
    { name: "Walnut butter", ingredients: ["noz"] },
    { name: "Whisky", ingredients: ["cevada", "malte"] },
    { name: "Whole grain bread", ingredients: ["farinha de trigo integral", "fermento", "sal"] },
    { name: "Whole grain pasta", ingredients: ["farinha de trigo integral"] },
    { name: "Wonton", ingredients: ["farinha de trigo", "carne", "temperos"] },
    { name: "Yakisoba", ingredients: ["macarrão", "legumes", "shoyu", "carne"] },
    { name: "Yogurt", ingredients: ["leite", "fermentos"] },
    { name: "Zabaglione", ingredients: ["ovo", "açúcar", "marsala"] },
    { name: "Zeppole", ingredients: ["trigo", "ovo", "ricota"] }
  ],
  pt: [
    { name: "Açaí", ingredients: ["polpa de açaí", "açúcar", "xarope de guaraná"] },
    { name: "Acarajé", ingredients: ["feijão fradinho", "dendê", "camarão"] },
    { name: "Amendoim cozido", ingredients: ["amendoim", "sal"] },
    { name: "Arroz carreteiro", ingredients: ["arroz", "carne seca"] },
    { name: "Arroz doce", ingredients: ["arroz", "leite", "açúcar", "canela"] },
    { name: "Babaganoush", ingredients: ["berinjela", "tahine", "alho"] },
    { name: "Bacon", ingredients: ["porco", "sal"] },
    { name: "Baguete", ingredients: ["trigo", "fermento", "sal"] },
    { name: "Baião de dois", ingredients: ["arroz", "feijão verde", "queijo coalho"] },
    { name: "Barra de gergelim", ingredients: ["gergelim", "açúcar", "mel"] },
    { name: "Beijinho", ingredients: ["leite condensado", "coco", "manteiga"] },
    { name: "Biscoito cream cracker", ingredients: ["trigo", "sal", "gordura vegetal"] },
    { name: "Biscoito de maisena", ingredients: ["trigo", "maisena", "açúcar", "manteiga", "ovo"] },
    { name: "Bobó de camarão", ingredients: ["camarão", "aipim", "leite de coco", "azeite de dendê", "cebola", "alho", "pimentão"] },
    { name: "Bolacha", ingredients: ["trigo", "açúcar", "manteiga"] },
    { name: "Bolo de rolo", ingredients: ["trigo", "açúcar", "ovo", "goiabada"] },
    { name: "Brigadeiro", ingredients: ["leite condensado", "chocolate", "manteiga", "leite"] },
    { name: "Broa de milho", ingredients: ["fubá", "farinha de trigo", "fermento"] },
    { name: "Bruschetta", ingredients: ["pão", "tomate", "azeite", "alho"] },
    { name: "Cajuzinho", ingredients: ["amendoim", "leite condensado", "chocolate"] },
    { name: "Camarão à paulista", ingredients: ["camarão", "alho", "manteiga"] },
    { name: "Camarão ao alho", ingredients: ["camarão", "alho", "azeite"] },
    { name: "Camarão cozido", ingredients: ["camarão", "sal"] },
    { name: "Camarão grelhado", ingredients: ["camarão"] },
    { name: "Canjica", ingredients: ["milho branco", "leite", "açúcar"] },
    { name: "Carne de sol", ingredients: ["carne bovina", "sal"] },
    { name: "Caruru", ingredients: ["quiabo", "camarão", "dendê"] },
    { name: "Castanha de baru torrada", ingredients: ["castanha de baru"] },
    { name: "Catchup", ingredients: ["tomate", "açúcar", "vinagre"] },
    { name: "Cerveja", ingredients: ["cevada", "lúpulo", "fermento"] },
    { name: "Chantilly", ingredients: ["creme de leite", "açúcar"] },
    { name: "Charque", ingredients: ["carne bovina", "sal"] },
    { name: "Chocolate ao leite", ingredients: ["cacau", "açúcar", "leite"] },
    { name: "Chocolate branco", ingredients: ["manteiga de cacau", "açúcar", "leite"] },
    { name: "Chopp", ingredients: ["cevada", "malte", "lúpulo", "fermento"] },
    { name: "Churros", ingredients: ["trigo", "açúcar", "ovo", "doce de leite"] },
    { name: "Ciabatta", ingredients: ["trigo", "fermento", "azeite"] },
    { name: "Cocada", ingredients: ["coco", "açúcar"] },
    { name: "Cottage cheese", ingredients: ["leite", "coalho", "sal"] },
    { name: "Coxinha", ingredients: ["trigo", "frango", "cebola", "alho"] },
    { name: "Cream cheese", ingredients: ["leite", "creme de leite"] },
    { name: "Cream cheese de soja", ingredients: ["soja", "óleo vegetal"] },
    { name: "Creme de amêndoa", ingredients: ["amêndoa", "açúcar"] },
    { name: "Creme de amendoim", ingredients: ["amendoim", "açúcar", "óleo"] },
    { name: "Creme de avelã", ingredients: ["avelã", "açúcar", "cacau"] },
    { name: "Creme de leite", ingredients: ["leite", "gordura"] },
    { name: "Creme de pistache", ingredients: ["pistache", "açúcar"] },
    { name: "Crepe", ingredients: ["trigo", "ovo", "leite"] },
    { name: "Croissant", ingredients: ["trigo", "manteiga", "fermento", "leite"] },
    { name: "Curau", ingredients: ["milho verde", "leite", "açúcar"] },
    { name: "Cuscuz", ingredients: ["milho", "sal"] },
    { name: "Cuscuz de milho", ingredients: ["fubá", "água", "sal"] },
    { name: "Cuscuz de trigo", ingredients: ["sêmola de trigo", "água"] },
    { name: "Doce de amendoim", ingredients: ["amendoim", "açúcar"] },
    { name: "Doce de leite", ingredients: ["leite", "açúcar"] },
    { name: "Empada", ingredients: ["trigo", "manteiga", "ovo"] },
    { name: "Empadão", ingredients: ["trigo", "frango", "palmito", "azeitona"] },
    { name: "Escondidinho", ingredients: ["mandioca", "carne", "queijo"] },
    { name: "Esfiha", ingredients: ["trigo", "fermento", "carne"] },
    { name: "Farofa", ingredients: ["mandioca", "manteiga"] },
    { name: "Feijoada", ingredients: ["feijão preto", "porco", "linguiça"] },
    { name: "Focaccia", ingredients: ["trigo", "azeite", "fermento"] },
    { name: "Galinhada", ingredients: ["arroz", "frango", "açafrão"] },
    { name: "Goiabada", ingredients: ["goiaba", "açúcar"] },
    { name: "Goma de mascar", ingredients: ["goma base", "açúcar", "aromatizante"] },
    { name: "Granola", ingredients: ["aveia", "mel", "castanhas"] },
    { name: "Guacamole", ingredients: ["abacate", "limão", "cebola", "tomate"] },
    { name: "Heineken", ingredients: ["cevada", "malte", "lúpulo", "fermento"] },
    { name: "Iogurte desnatado", ingredients: ["leite desnatado", "fermentos"] },
    { name: "Iogurte grego", ingredients: ["leite", "creme de leite", "fermentos"] },
    { name: "Iogurte natural", ingredients: ["leite", "fermentos"] },
    { name: "Jabá", ingredients: ["carne bovina", "sal"] },
    { name: "Ketchup", ingredients: ["tomate", "açúcar", "vinagre"] },
    { name: "Lasanha", ingredients: ["trigo", "ovo", "queijo", "leite", "carne"] },
    { name: "Leite condensado", ingredients: ["leite", "açúcar"] },
    { name: "Leite de soja", ingredients: ["soja", "água"] },
    { name: "Linguiça", ingredients: ["porco", "sal", "páprica"] },
    { name: "Maionese", ingredients: ["ovo", "óleo", "vinagre"] },
    { name: "Maionese caseira", ingredients: ["ovo", "óleo", "limão"] },
    { name: "Maionese de soja", ingredients: ["soja", "óleo vegetal"] },
    { name: "Manteiga", ingredients: ["leite", "sal"] },
    { name: "Maria mole", ingredients: ["açúcar", "clara de ovo", "coco"] },
    { name: "Mingau", ingredients: ["leite", "amido"] },
    { name: "Mingau de fubá", ingredients: ["fubá", "leite", "açúcar"] },
    { name: "Mingau de milho", ingredients: ["milho", "leite", "açúcar"] },
    { name: "Molho bechamel", ingredients: ["leite", "manteiga", "trigo"] },
    { name: "Molho branco", ingredients: ["leite", "manteiga", "trigo"] },
    { name: "Molho de soja", ingredients: ["soja", "trigo", "sal"] },
    { name: "Molho de tomate", ingredients: ["tomate", "cebola", "alho", "azeite"] },
    { name: "Molho pesto", ingredients: ["manjericão", "parmesão", "alho", "azeite", "castanha"] },
    { name: "Molho rosé", ingredients: ["tomate", "creme de leite"] },
    { name: "Molho teriyaki", ingredients: ["shoyu", "açúcar", "gengibre"] },
    { name: "Moqueca", ingredients: ["peixe", "leite de coco", "dendê", "pimentão"] },
    { name: "Moqueca de camarão", ingredients: ["camarão", "leite de coco", "azeite de dendê", "tomate", "pimentão", "cebola", "coentro"] },
    { name: "Moqueca de peixe", ingredients: ["peixe", "leite de coco", "azeite de dendê", "tomate", "pimentão", "cebola", "coentro"] },
    { name: "Mortadela", ingredients: ["carne", "porco", "sal"] },
    { name: "Mostarda", ingredients: ["semente de mostarda", "vinagre"] },
    { name: "Muesli", ingredients: ["aveia", "frutas secas", "castanhas"] },
    { name: "Nhoque", ingredients: ["batata", "trigo", "ovo"] },
    { name: "Nougat de amendoim", ingredients: ["amendoim", "açúcar", "clara de ovo"] },
    { name: "Omelete", ingredients: ["ovo", "óleo", "sal"] },
    { name: "Paçoca", ingredients: ["amendoim", "açúcar", "sal"] },
    { name: "Paçoca de colher", ingredients: ["amendoim", "açúcar", "farinha"] },
    { name: "Pamonha", ingredients: ["milho verde", "leite"] },
    { name: "Pamonha doce", ingredients: ["milho", "açúcar", "leite"] },
    { name: "Pão de forma", ingredients: ["trigo", "fermento", "sal", "açúcar"] },
    { name: "Pão de mel", ingredients: ["mel", "trigo", "chocolate", "especiarias"] },
    { name: "Pão de queijo", ingredients: ["polvilho", "queijo", "ovo", "leite"] },
    { name: "Pão francês", ingredients: ["trigo", "fermento", "sal"] },
    { name: "Pão integral", ingredients: ["trigo integral", "fermento", "sal"] },
    { name: "Pastel", ingredients: ["trigo", "sal", "óleo"] },
    { name: "Pato no tucupi", ingredients: ["pato", "tucupi", "jambu"] },
    { name: "Pé de moleque", ingredients: ["amendoim", "açúcar"] },
    { name: "Pecan butter", ingredients: ["noz-pecã"] },
    { name: "Pirão de peixe", ingredients: ["farinha de mandioca", "caldo de peixe"] },
    { name: "Polenta", ingredients: ["milho"] },
    { name: "Pudim", ingredients: ["leite", "ovo", "açúcar", "leite condensado"] },
    { name: "Quiche", ingredients: ["trigo", "ovo", "leite", "queijo"] },
    { name: "Quindim", ingredients: ["ovo", "açúcar", "coco"] },
    { name: "Ravioli", ingredients: ["trigo", "ovo", "queijo"] },
    { name: "Requeijão", ingredients: ["leite", "creme de leite"] },
    { name: "Risole", ingredients: ["farinha de trigo", "ovo", "recheio"] },
    { name: "Romeu e julieta", ingredients: ["queijo", "goiabada"] },
    { name: "Rosca", ingredients: ["farinha de trigo", "açúcar", "fermento"] },
    { name: "Sabor amendoim", ingredients: ["amendoim", "aromatizante"] },
    { name: "Sonho", ingredients: ["trigo", "fermento", "ovo", "creme"] },
    { name: "Strogonoff", ingredients: ["carne", "creme de leite", "cogumelo"] },
    { name: "Suco de laranja", ingredients: ["laranja"] },
    { name: "Suco de uva", ingredients: ["uva"] },
    { name: "Suflê", ingredients: ["ovo", "queijo", "leite"] },
    { name: "Tacacá", ingredients: ["tucupi", "jambu", "camarão", "goma"] },
    { name: "Tahine", ingredients: ["gergelim"] },
    { name: "Tapioca", ingredients: ["mandioca"] },
    { name: "Tempeh", ingredients: ["soja"] },
    { name: "Tofu", ingredients: ["soja"] },
    { name: "Tofu frito", ingredients: ["tofu", "óleo"] },
    { name: "Tofu grelhado", ingredients: ["tofu"] },
    { name: "Torrone de amendoim", ingredients: ["amendoim", "açúcar", "mel", "clara de ovo"] },
    { name: "Tropeiro", ingredients: ["feijão", "farinha de mandioca", "ovo", "linguiça"] },
    { name: "Tutu", ingredients: ["feijão", "farinha de mandioca"] },
    { name: "Vatapá", ingredients: ["pão", "amendoim", "castanha", "camarão", "dendê"] },
    { name: "Vinagrete", ingredients: ["tomate", "cebola", "pimentão", "vinagre"] },
    { name: "Vitamina de frutas", ingredients: ["frutas", "leite", "açúcar"] },
    { name: "Waffle", ingredients: ["trigo", "ovo", "leite", "manteiga", "açúcar"] }
  ]
};

async function importComplete() {
  try {
    const allData = [
      ...foodDecomposition.en.map(f => ({
        food_name: f.name.toLowerCase(),
        base_ingredients: f.ingredients,
        language: 'en',
        is_active: true
      })),
      ...foodDecomposition.pt.map(f => ({
        food_name: f.name.toLowerCase(),
        base_ingredients: f.ingredients,
        language: 'pt',
        is_active: true
      }))
    ];
    
    console.log(`📊 Total: ${allData.length} (EN: ${foodDecomposition.en.length}, PT: ${foodDecomposition.pt.length})\n`);
    
    console.log("🗑️ Limpando...");
    await supabase.from('food_decomposition_mappings').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    
    console.log("📥 Inserindo...\n");
    const batchSize = 50;
    let totalInserted = 0;
    
    for (let i = 0; i < allData.length; i += batchSize) {
      const batch = allData.slice(i, i + batchSize);
      const { data, error } = await supabase
        .from('food_decomposition_mappings')
        .insert(batch)
        .select();
      
      if (error) {
        console.error(`❌ Lote ${Math.floor(i / batchSize) + 1}: ${error.message}`);
      } else {
        totalInserted += data.length;
        console.log(`✅ Lote ${Math.floor(i / batchSize) + 1}: ${data.length}`);
      }
    }
    
    const { count } = await supabase
      .from('food_decomposition_mappings')
      .select('*', { count: 'exact', head: true });
    
    console.log("\n" + "=".repeat(60));
    console.log("🎉 IMPORTAÇÃO COMPLETA!");
    console.log("=".repeat(60));
    console.log(`✅ Inseridos: ${totalInserted}`);
    console.log(`📈 Total no banco: ${count || 0}`);
    
  } catch (error) {
    console.error('❌ Erro:', error);
  }
}

importComplete();
