/**
 * INTOLERANCE MEAL POOL
 * 
 * Pool de refeições seguras para cada uma das 17 intolerâncias do sistema.
 * 30 opções x 6 tipos de refeição x 17 intolerâncias = 3.060 refeições
 * 
 * Usado por:
 * - generate-ai-meal-plan
 * - regenerate-ai-meal-alternatives
 * - analyze-food-photo (sugestões seguras)
 * 
 * MEAL_TYPE KEYS (English standard):
 * - breakfast (cafe_manha)
 * - morning_snack (lanche_manha)
 * - lunch (almoco)
 * - afternoon_snack (lanche_tarde)
 * - dinner (jantar)
 * - supper (ceia)
 */

// Tipo de refeição com arrays de opções
type MealTypePool = Record<string, string[]>;

// Pool completo de intolerâncias
type IntolerancePoolType = Record<string, MealTypePool>;

// ============= INTOLERANCE MEAL POOL =============
export const INTOLERANCE_MEAL_POOL: IntolerancePoolType = {

  // ============= SEM GLÚTEN (180 itens) =============
  'gluten': {
    'breakfast': [
      'Tapioca de queijo branco com ovo mexido',
      'Mingau de aveia sem glúten com frutas vermelhas',
      'Omelete com vegetais e queijo minas',
      'Pão de queijo com requeijão light',
      'Smoothie de frutas com granola sem glúten',
      'Crepioca de frango (tapioca + ovo)',
      'Panqueca de banana com aveia sem glúten',
      'Iogurte grego com mel, chia e frutas',
      'Bolo de fubá sem glúten com café',
      'Vitamina de mamão com aveia sem glúten',
      'Pão de queijo recheado com presunto e queijo',
      'Tapioca doce com coco ralado e leite condensado',
      'Mingau de quinoa com canela e maçã',
      'Omelete de forno com brócolis e queijo',
      'Crepioca com pasta de amendoim e banana',
      'Smoothie bowl com frutas e coco ralado',
      'Panqueca de batata-doce com queijo cottage',
      'Bolo de mandioca sem glúten',
      'Tapioca de atum com cream cheese',
      'Vitamina de abacate com cacau',
      'Pão de queijo de frigideira',
      'Mingau de amaranto com frutas secas',
      'Omelete caprese (tomate, manjericão e mussarela)',
      'Crepioca pizza (molho de tomate e queijo)',
      'Panqueca de banana e aveia com mel',
      'Iogurte com granola sem glúten e geleia',
      'Tapioca de queijo coalho grelhado',
      'Smoothie de frutas tropicais com linhaça',
      'Bolo de cenoura sem glúten com cobertura de chocolate',
      'Mingau de polvilho doce com leite de coco',
    ],
    'morning_snack': [
      'Iogurte natural com mel e amêndoas',
      'Castanhas e nozes variadas',
      'Banana com pasta de amendoim',
      'Queijo branco com tomate cereja',
      'Vitamina de frutas vermelhas',
      'Chips de batata-doce assada',
      'Mix de frutas secas e castanhas',
      'Queijo minas com geleia de frutas',
      'Smoothie de morango com chia',
      'Biscoitos de polvilho assados',
      'Maçã com pasta de amêndoa',
      'Iogurte com granola sem glúten',
      'Palitos de cenoura com homus',
      'Frutas picadas com coco ralado',
      'Castanha de caju torrada',
      'Queijo cottage com abacaxi',
      'Vitamina de banana com aveia',
      'Pipoca caseira sem manteiga',
      'Pera com queijo brie',
      'Mix de nuts e sementes',
      'Iogurte batido com frutas',
      'Tomate cereja com mussarela de búfala',
      'Smoothie verde com espinafre',
      'Biscoitos de arroz com geleia',
      'Uvas congeladas',
      'Queijo prato com damasco',
      'Vitamina de manga com coco',
      'Chips de abobrinha assada',
      'Frutas com iogurte grego',
      'Barra de proteína sem glúten',
    ],
    'lunch': [
      'Arroz com feijão, frango grelhado e salada verde',
      'Batata-doce assada com carne moída e legumes refogados',
      'Risoto de quinoa com camarão e brócolis',
      'Peixe assado com purê de abóbora e acelga',
      'Macarrão de arroz com molho de tomate e almôndegas',
      'Polenta cremosa com ragu de carne',
      'Arroz integral com lentilha, omelete e salada',
      'Carne assada com batatas rústicas e couve refogada',
      'Risoto de cogumelos com filé mignon',
      'Tilápia grelhada com arroz e legumes no vapor',
      'Macarrão de abobrinha com molho bolonhesa',
      'Frango xadrez com arroz basmati',
      'Escondidinho de carne com mandioca',
      'Salmão grelhado com purê de batata-doce',
      'Arroz com feijão preto, linguiça e couve',
      'Carne de panela com polenta mole',
      'Risoto de abóbora com frango desfiado',
      'Peixe ao molho de limão com arroz integral',
      'Macarrão de arroz com camarão ao alho',
      'Frango assado com batata e cenoura',
      'Arroz de couve-flor com carne moída',
      'Filé de frango com purê de mandioquinha',
      'Risoto de beterraba com queijo de cabra',
      'Peixe ensopado com pirão de mandioca',
      'Arroz com grão-de-bico, frango e salada',
      'Carne moída com batata-doce e espinafre',
      'Polenta grelhada com ragu de linguiça',
      'Tilápia com crosta de ervas e legumes',
      'Arroz negro com frutos do mar',
      'Frango ao curry com arroz jasmim',
    ],
    'afternoon_snack': [
      'Pipoca caseira com azeite',
      'Frutas picadas com coco ralado',
      'Biscoitos de polvilho doce',
      'Homus com cenoura baby',
      'Gelatina com frutas frescas',
      'Bolo de fubá sem glúten',
      'Iogurte com mel e granola',
      'Chips de banana assada',
      'Queijo branco com geleia',
      'Vitamina de frutas tropicais',
      'Mix de castanhas torradas',
      'Pão de queijo pequeno',
      'Frutas desidratadas',
      'Smoothie de abacate',
      'Biscoitos de arroz com pasta de amendoim',
      'Queijo cottage com mel',
      'Tapioca mini com queijo',
      'Pipoca doce com coco',
      'Iogurte grego com frutas vermelhas',
      'Chips de maçã assada',
      'Castanhas caramelizadas',
      'Gelatina diet com coco',
      'Bolo de banana sem glúten',
      'Vitamina de mamão com aveia',
      'Queijo minas com damasco',
      'Crepioca doce com canela',
      'Frutas assadas com mel',
      'Biscoitos de polvilho com queijo',
      'Smoothie de manga',
      'Iogurte batido com chia',
    ],
    'dinner': [
      'Sopa de legumes com frango desfiado',
      'Omelete de forno com espinafre e queijo',
      'Escondidinho de carne com mandioca',
      'Salada completa com atum e grão-de-bico',
      'Wrap de alface com frango e vegetais',
      'Creme de abóbora com gengibre',
      'Omelete de brócolis com queijo',
      'Sopa de quinoa com legumes',
      'Salada Caesar sem croutons com frango',
      'Wrap de alface com carne moída',
      'Creme de mandioquinha com frango',
      'Omelete caprese com salada',
      'Sopa de lentilha com legumes',
      'Salada de folhas com salmão grelhado',
      'Wrap de couve com atum',
      'Creme de espinafre com queijo',
      'Omelete de cogumelos',
      'Sopa de batata-doce com carne',
      'Salada morna com frango e quinoa',
      'Wrap de alface com camarão',
      'Creme de brócolis com bacon',
      'Omelete de legumes variados',
      'Sopa de grão-de-bico com vegetais',
      'Salada de rúcula com filé mignon',
      'Wrap de alface com frango ao curry',
      'Creme de cenoura com gengibre',
      'Omelete simples com salada verde',
      'Sopa de feijão branco com linguiça',
      'Salada completa com ovos cozidos',
      'Wrap de alface com peixe grelhado',
    ],
    'supper': [
      'Chá com biscoitos de polvilho',
      'Iogurte natural com chia',
      'Frutas assadas com canela',
      'Leite vegetal com amaranto',
      'Gelatina diet',
      'Castanhas variadas (porção pequena)',
      'Chá de camomila com mel',
      'Iogurte grego simples',
      'Maçã assada com canela',
      'Leite de amêndoas morno',
      'Gelatina com pedaços de fruta',
      'Mix de nuts (pequena porção)',
      'Chá verde com biscoitos de arroz',
      'Iogurte com mel',
      'Banana cozida com canela',
      'Leite de coco morno',
      'Gelatina de frutas vermelhas',
      'Castanhas de caju (5 unidades)',
      'Chá de erva-doce',
      'Iogurte batido com morango',
      'Pera cozida',
      'Leite vegetal com cacau',
      'Gelatina light',
      'Amêndoas torradas (pequena porção)',
      'Chá de hortelã',
      'Iogurte com coco ralado',
      'Frutas picadas (porção pequena)',
      'Leite de arroz morno',
      'Gelatina com coco',
      'Nozes (porção pequena)',
    ],
  },

  // ============= SEM LACTOSE (180 itens) =============
  'lactose': {
    'breakfast': [
      'Pão integral com geleia e pasta de amendoim',
      'Mingau de aveia com leite de amêndoas',
      'Panqueca com banana e mel (leite vegetal)',
      'Smoothie com leite de coco e frutas',
      'Torrada com abacate amassado',
      'Granola com leite vegetal',
      'Pão sem lactose com geleia de morango',
      'Mingau de quinoa com leite de aveia',
      'Panqueca de banana e aveia',
      'Smoothie bowl com frutas e granola',
      'Torrada integral com pasta de amendoim',
      'Aveia overnight com leite de coco',
      'Pão de forma sem lactose com ovo',
      'Mingau de amaranto com frutas',
      'Panqueca proteica com mel',
      'Smoothie verde com espinafre',
      'Torrada com geleia de frutas vermelhas',
      'Granola caseira com leite de arroz',
      'Pão integral com abacate',
      'Mingau de chia com leite vegetal',
      'Panqueca de batata-doce',
      'Smoothie de manga com coco',
      'Torrada com pasta de grão-de-bico',
      'Aveia com frutas e canela',
      'Pão sem lactose com atum',
      'Mingau de tapioca com leite de coco',
      'Panqueca de espinafre',
      'Smoothie de frutas vermelhas',
      'Torrada com tomate e azeite',
      'Granola com iogurte vegetal',
    ],
    'morning_snack': [
      'Frutas frescas variadas',
      'Mix de oleaginosas (castanhas e nozes)',
      'Barra de cereais sem lactose',
      'Cookies de aveia e banana',
      'Suco verde detox',
      'Hummus com palitos de pepino',
      'Maçã com pasta de amendoim',
      'Chips de banana desidratada',
      'Smoothie de abacate',
      'Biscoitos de arroz com geleia',
      'Frutas secas variadas',
      'Mix de nuts e sementes',
      'Barra de proteína vegetal',
      'Cookies integrais sem lactose',
      'Suco de laranja natural',
      'Guacamole com palitos de cenoura',
      'Pera com pasta de amêndoa',
      'Chips de maçã desidratada',
      'Smoothie de morango',
      'Biscoitos de aveia caseiros',
      'Uvas e morangos',
      'Castanhas caramelizadas',
      'Barra energética caseira',
      'Cookies de chocolate sem lactose',
      'Suco de melancia',
      'Homus com pepino',
      'Banana com granola',
      'Chips de coco',
      'Smoothie tropical',
      'Biscoitos integrais simples',
    ],
    'lunch': [
      'Arroz integral, feijão, carne e salada',
      'Macarrão integral ao sugo com frango',
      'Peixe grelhado com legumes assados',
      'Risoto de cogumelos (com creme vegetal)',
      'Carne de panela com batatas',
      'Frango ao curry com arroz basmati',
      'Arroz com lentilha e bife grelhado',
      'Macarrão com molho pesto sem queijo',
      'Salmão assado com quinoa',
      'Risoto de abóbora sem queijo',
      'Bife acebolado com arroz e feijão',
      'Frango xadrez com legumes',
      'Arroz negro com camarão',
      'Macarrão ao alho e óleo com frango',
      'Peixe ao molho de tomate com arroz',
      'Carne moída com batata-doce',
      'Frango grelhado com purê de mandioquinha',
      'Arroz com grão-de-bico e salada',
      'Macarrão com brócolis e alho',
      'Tilápia com legumes no vapor',
      'Estrogonofe sem creme de leite (creme vegetal)',
      'Frango assado com batatas rústicas',
      'Arroz de couve-flor com carne',
      'Macarrão com molho de tomate caseiro',
      'Peixe grelhado com salada de quinoa',
      'Carne assada com purê de abóbora',
      'Frango ao limão com arroz integral',
      'Arroz com feijão preto e linguiça',
      'Macarrão com abobrinha e tomate',
      'Salmão com crosta de ervas',
    ],
    'afternoon_snack': [
      'Pipoca com azeite e sal',
      'Pão sem lactose com pasta de atum',
      'Frutas com granola sem lactose',
      'Bolo caseiro sem lactose',
      'Vitamina com leite vegetal',
      'Tapioca de coco ralado',
      'Chips de batata-doce',
      'Pão integral com geleia',
      'Frutas picadas com mel',
      'Bolo de banana sem lactose',
      'Smoothie de frutas tropicais',
      'Biscoitos de aveia caseiros',
      'Pipoca doce com açúcar mascavo',
      'Pão com pasta de abacate',
      'Frutas desidratadas',
      'Bolo de cenoura sem lactose',
      'Vitamina de morango',
      'Cookies sem lactose',
      'Pipoca salgada caseira',
      'Pão com homus',
      'Salada de frutas',
      'Bolo de chocolate sem lactose',
      'Smoothie verde',
      'Biscoitos integrais',
      'Tapioca de geleia de frutas',
      'Pão com pasta de grão-de-bico',
      'Frutas com granola caseira',
      'Bolo de fubá sem lactose',
      'Vitamina de manga',
      'Crackers com pasta vegetal',
    ],
    'dinner': [
      'Sopa de lentilha com legumes',
      'Omelete com legumes (sem queijo)',
      'Salada Caesar adaptada (sem parmesão)',
      'Wrap integral com frango e salada',
      'Peixe com purê de batata (leite vegetal)',
      'Strogonoff vegano de cogumelos',
      'Sopa de legumes com carne moída',
      'Omelete de espinafre',
      'Salada completa com frango grelhado',
      'Wrap de alface com atum',
      'Salmão grelhado com legumes',
      'Risoto sem queijo com frango',
      'Sopa de batata-doce com gengibre',
      'Omelete simples com salada',
      'Salada morna de quinoa',
      'Wrap integral com carne',
      'Peixe ao forno com ervas',
      'Creme de legumes sem creme de leite',
      'Sopa de grão-de-bico',
      'Omelete de tomate',
      'Salada de rúcula com salmão',
      'Wrap de frango ao curry',
      'Tilápia grelhada com salada',
      'Sopa de feijão branco',
      'Omelete de cogumelos',
      'Salada completa com atum',
      'Wrap vegetal com homus',
      'Peixe com legumes assados',
      'Sopa de mandioquinha',
      'Omelete de brócolis com salada',
    ],
    'supper': [
      'Chá com biscoitos sem lactose',
      'Frutas desidratadas',
      'Leite vegetal com aveia',
      'Banana assada com canela',
      'Gelatina',
      'Amendoim torrado',
      'Chá de camomila',
      'Smoothie leve de frutas',
      'Maçã assada',
      'Leite de coco morno',
      'Gelatina de frutas',
      'Castanhas variadas',
      'Chá verde',
      'Vitamina leve',
      'Pera cozida',
      'Leite de amêndoas',
      'Gelatina diet',
      'Mix de nuts',
      'Chá de erva-doce',
      'Frutas frescas',
      'Banana com canela',
      'Leite vegetal com cacau',
      'Gelatina com frutas',
      'Nozes (pequena porção)',
      'Chá de hortelã',
      'Smoothie de morango',
      'Frutas picadas',
      'Leite de arroz',
      'Gelatina light',
      'Amêndoas torradas',
    ],
  },

  // ============= SEM AMENDOIM (180 itens) =============
  'amendoim': {
    'breakfast': [
      'Pão com geleia de frutas vermelhas',
      'Mingau com castanhas de caju',
      'Tapioca com queijo cottage',
      'Smoothie de frutas vermelhas',
      'Panqueca com mel e frutas',
      'Iogurte com granola (sem amendoim)',
      'Pão integral com queijo branco',
      'Mingau de aveia com banana',
      'Crepioca com presunto e queijo',
      'Smoothie bowl com frutas',
      'Panqueca de banana',
      'Iogurte grego com mel',
      'Pão com requeijão light',
      'Mingau de quinoa',
      'Tapioca de coco ralado',
      'Smoothie verde',
      'Panqueca integral',
      'Iogurte com frutas frescas',
      'Pão com abacate',
      'Mingau de amaranto',
      'Crepioca com frango',
      'Smoothie tropical',
      'Panqueca de aveia',
      'Iogurte com granola caseira',
      'Pão com geleia de morango',
      'Mingau de chia',
      'Tapioca de queijo minas',
      'Smoothie de manga',
      'Panqueca proteica',
      'Iogurte batido com frutas',
    ],
    'morning_snack': [
      'Frutas da estação variadas',
      'Castanhas variadas (exceto amendoim)',
      'Queijo branco com mel',
      'Bolo de banana',
      'Vitamina de morango',
      'Biscoitos de aveia',
      'Maçã com queijo',
      'Nozes e amêndoas',
      'Iogurte natural',
      'Bolo de cenoura',
      'Smoothie de frutas',
      'Biscoitos integrais',
      'Pera com queijo brie',
      'Castanhas de caju',
      'Vitamina de abacate',
      'Bolo de fubá',
      'Frutas secas',
      'Mix de nuts (sem amendoim)',
      'Iogurte com mel',
      'Bolo de chocolate',
      'Smoothie verde',
      'Biscoitos de arroz',
      'Queijo cottage com frutas',
      'Macadâmia torrada',
      'Vitamina de banana',
      'Bolo caseiro',
      'Frutas picadas',
      'Castanhas do Pará',
      'Iogurte grego',
      'Smoothie tropical',
    ],
    'lunch': [
      'Arroz, feijão, carne assada e salada',
      'Macarrão à carbonara',
      'Frango xadrez com legumes',
      'Peixe grelhado com arroz integral',
      'Lasanha de berinjela',
      'Feijoada light',
      'Arroz com lentilha e bife',
      'Macarrão ao molho branco',
      'Frango grelhado com quinoa',
      'Salmão com legumes',
      'Risoto de cogumelos',
      'Carne de panela',
      'Arroz integral com frango',
      'Macarrão ao pesto',
      'Peixe ao forno',
      'Estrogonofe de carne',
      'Frango ao curry',
      'Arroz com grão-de-bico',
      'Macarrão à bolonhesa',
      'Tilápia grelhada',
      'Risoto de frango',
      'Carne assada com batatas',
      'Arroz de couve-flor',
      'Macarrão com brócolis',
      'Peixe empanado',
      'Frango xadrez',
      'Arroz negro',
      'Macarrão integral',
      'Salmão grelhado',
      'Risoto de camarão',
    ],
    'afternoon_snack': [
      'Pipoca caseira',
      'Pão de queijo',
      'Frutas com mel',
      'Bolo de fubá',
      'Suco de laranja natural',
      'Biscoitos de maisena',
      'Tapioca de queijo branco',
      'Iogurte com frutas',
      'Chips de batata-doce',
      'Bolo de banana',
      'Vitamina de morango',
      'Biscoitos integrais',
      'Queijo com geleia',
      'Castanhas (sem amendoim)',
      'Smoothie de frutas',
      'Bolo de cenoura',
      'Pipoca doce',
      'Pão com geleia',
      'Frutas desidratadas',
      'Bolo caseiro',
      'Suco verde',
      'Biscoitos de arroz',
      'Tapioca doce',
      'Iogurte grego',
      'Chips de maçã',
      'Bolo de chocolate',
      'Vitamina de banana',
      'Crackers integrais',
      'Queijo branco',
      'Smoothie tropical',
    ],
    'dinner': [
      'Sopa de legumes com carne',
      'Omelete caprese',
      'Sanduíche natural de frango',
      'Salada completa com grelhados',
      'Risoto de frango',
      'Crepe integral recheado',
      'Sopa de mandioquinha',
      'Omelete de brócolis',
      'Wrap de frango',
      'Salada Caesar',
      'Creme de legumes',
      'Panqueca salgada',
      'Sopa de lentilha',
      'Omelete simples',
      'Sanduíche integral',
      'Salada morna',
      'Risoto de cogumelos',
      'Crepe de espinafre',
      'Sopa de abóbora',
      'Omelete de queijo',
      'Wrap integral',
      'Salada completa',
      'Creme de brócolis',
      'Panqueca de carne',
      'Sopa de feijão',
      'Omelete de tomate',
      'Sanduíche leve',
      'Salada de quinoa',
      'Risoto light',
      'Crepe de frango',
    ],
    'supper': [
      'Chá com torradas',
      'Iogurte com mel',
      'Frutas assadas',
      'Leite com aveia',
      'Gelatina',
      'Castanhas (sem amendoim)',
      'Chá de camomila',
      'Frutas frescas',
      'Banana cozida',
      'Leite morno',
      'Gelatina diet',
      'Nozes',
      'Chá verde',
      'Iogurte natural',
      'Maçã assada',
      'Leite vegetal',
      'Gelatina de frutas',
      'Amêndoas',
      'Chá de hortelã',
      'Smoothie leve',
      'Pera cozida',
      'Leite com mel',
      'Gelatina light',
      'Castanhas de caju',
      'Chá de erva-doce',
      'Frutas picadas',
      'Banana com canela',
      'Leite morno com cacau',
      'Gelatina com coco',
      'Macadâmia',
    ],
  },

  // ============= SEM OLEAGINOSAS (180 itens) =============
  'oleaginosas': {
    'breakfast': [
      'Pão francês com manteiga e geleia',
      'Mingau de aveia simples',
      'Panqueca americana com mel',
      'Iogurte com frutas e granola básica',
      'Bolo simples com suco',
      'Torrada com queijo branco',
      'Pão integral com geleia',
      'Mingau de fubá',
      'Panqueca de banana',
      'Iogurte grego com mel',
      'Bolo de fubá',
      'Torrada com requeijão',
      'Pão com queijo minas',
      'Mingau de tapioca',
      'Panqueca proteica',
      'Iogurte com frutas',
      'Bolo de cenoura',
      'Torrada com abacate',
      'Pão com presunto e queijo',
      'Mingau de quinoa',
      'Panqueca integral',
      'Iogurte batido',
      'Bolo de banana',
      'Torrada com geleia',
      'Pão de queijo',
      'Mingau de aveia com frutas',
      'Panqueca doce',
      'Iogurte com granola simples',
      'Bolo caseiro',
      'Torrada integral',
    ],
    'morning_snack': [
      'Frutas frescas variadas',
      'Iogurte natural',
      'Biscoitos maria',
      'Bolo de milho',
      'Vitamina de banana',
      'Queijo com bolacha cream cracker',
      'Maçã com queijo',
      'Iogurte grego',
      'Biscoitos de maisena',
      'Bolo de fubá',
      'Smoothie de frutas',
      'Queijo branco',
      'Pera fresca',
      'Iogurte com mel',
      'Biscoitos integrais',
      'Bolo caseiro',
      'Vitamina de morango',
      'Queijo cottage',
      'Banana com mel',
      'Iogurte batido',
      'Biscoitos simples',
      'Bolo de cenoura',
      'Smoothie tropical',
      'Queijo minas',
      'Frutas picadas',
      'Iogurte com frutas',
      'Biscoitos de arroz',
      'Bolo de chocolate',
      'Vitamina verde',
      'Queijo com geleia',
    ],
    'lunch': [
      'Arroz, feijão, bife e salada',
      'Macarrão ao molho branco',
      'Frango assado com legumes',
      'Peixe com purê de batata',
      'Estrogonofe de carne',
      'Arroz de forno com frango',
      'Macarrão à carbonara',
      'Bife grelhado com arroz',
      'Frango xadrez',
      'Salmão com legumes',
      'Risoto simples',
      'Carne de panela',
      'Macarrão ao sugo',
      'Frango grelhado',
      'Peixe assado',
      'Feijoada light',
      'Arroz integral',
      'Macarrão ao pesto',
      'Bife acebolado',
      'Frango ao molho',
      'Tilápia grelhada',
      'Risoto de frango',
      'Carne assada',
      'Macarrão integral',
      'Frango empanado',
      'Peixe ao forno',
      'Arroz com lentilha',
      'Macarrão com brócolis',
      'Bife à parmegiana',
      'Frango ao curry',
    ],
    'afternoon_snack': [
      'Pipoca caseira',
      'Pão de queijo',
      'Frutas com mel',
      'Bolo de fubá',
      'Suco de laranja',
      'Biscoitos de maisena',
      'Tapioca de queijo branco',
      'Iogurte com frutas',
      'Chips de batata',
      'Bolo de banana',
      'Vitamina de morango',
      'Biscoitos integrais',
      'Queijo com geleia',
      'Pipoca doce',
      'Smoothie de frutas',
      'Bolo de cenoura',
      'Pão com geleia',
      'Frutas frescas',
      'Iogurte grego',
      'Biscoitos simples',
      'Bolo caseiro',
      'Suco natural',
      'Tapioca doce',
      'Vitamina de banana',
      'Chips caseiros',
      'Bolo de chocolate',
      'Queijo branco',
      'Biscoitos de arroz',
      'Smoothie tropical',
      'Iogurte batido',
    ],
    'dinner': [
      'Sopa de mandioquinha com carne',
      'Omelete simples com salada',
      'Sanduíche de frango',
      'Salada Caesar (sem nuts)',
      'Risoto de camarão',
      'Pizza caseira integral',
      'Sopa de legumes',
      'Omelete de queijo',
      'Wrap de frango',
      'Salada completa',
      'Creme de abóbora',
      'Panqueca salgada',
      'Sopa de lentilha',
      'Omelete caprese',
      'Sanduíche integral',
      'Salada morna',
      'Risoto de frango',
      'Crepe recheado',
      'Sopa de feijão',
      'Omelete de brócolis',
      'Wrap integral',
      'Salada de quinoa',
      'Creme de brócolis',
      'Pizza de frigideira',
      'Sopa de batata',
      'Omelete de tomate',
      'Sanduíche natural',
      'Salada verde',
      'Risoto simples',
      'Crepe de espinafre',
    ],
    'supper': [
      'Chá com torradas',
      'Iogurte com mel',
      'Frutas assadas',
      'Leite com aveia',
      'Gelatina',
      'Biscoitos simples',
      'Chá de camomila',
      'Frutas frescas',
      'Banana cozida',
      'Leite morno',
      'Gelatina diet',
      'Torradas com geleia',
      'Chá verde',
      'Iogurte natural',
      'Maçã assada',
      'Leite com mel',
      'Gelatina de frutas',
      'Biscoitos maria',
      'Chá de hortelã',
      'Smoothie leve',
      'Pera cozida',
      'Leite com cacau',
      'Gelatina light',
      'Crackers simples',
      'Chá de erva-doce',
      'Frutas picadas',
      'Banana com canela',
      'Leite morno simples',
      'Gelatina com frutas',
      'Biscoitos de maisena',
    ],
  },

  // ============= SEM FRUTOS DO MAR (180 itens) =============
  'frutos_do_mar': {
    'breakfast': [
      'Pão integral com ovo mexido',
      'Mingau de aveia com frutas',
      'Panqueca com queijo e presunto',
      'Smoothie verde com espinafre',
      'Tapioca de frango desfiado',
      'Wrap de omelete',
      'Pão com queijo e tomate',
      'Mingau de quinoa',
      'Panqueca proteica',
      'Smoothie de frutas tropicais',
      'Crepioca com carne',
      'Omelete de forno',
      'Pão integral com requeijão',
      'Mingau de aveia com banana',
      'Panqueca de batata-doce',
      'Smoothie de morango',
      'Tapioca de queijo minas',
      'Wrap de frango',
      'Pão com geleia',
      'Mingau de fubá',
      'Panqueca integral',
      'Smoothie bowl',
      'Crepioca com presunto',
      'Omelete caprese',
      'Pão de queijo',
      'Mingau de tapioca',
      'Panqueca de banana',
      'Smoothie de abacate',
      'Tapioca doce',
      'Wrap vegetariano',
    ],
    'morning_snack': [
      'Frutas variadas',
      'Mix de nuts',
      'Queijo com uvas',
      'Bolo de banana',
      'Vitamina de abacate',
      'Biscoitos integrais',
      'Maçã com queijo',
      'Castanhas variadas',
      'Iogurte com granola',
      'Bolo de cenoura',
      'Smoothie de frutas',
      'Biscoitos de aveia',
      'Pera com queijo brie',
      'Mix de oleaginosas',
      'Vitamina de morango',
      'Bolo de fubá',
      'Frutas secas',
      'Amêndoas torradas',
      'Iogurte grego',
      'Bolo caseiro',
      'Smoothie verde',
      'Biscoitos integrais',
      'Queijo cottage',
      'Nozes e castanhas',
      'Vitamina de banana',
      'Bolo de chocolate',
      'Frutas frescas',
      'Castanhas de caju',
      'Iogurte com mel',
      'Smoothie tropical',
    ],
    'lunch': [
      'Arroz, feijão, frango e legumes',
      'Macarrão à bolonhesa',
      'Bife grelhado com batata-doce',
      'Frango xadrez com arroz',
      'Lasanha de carne',
      'Feijoada completa',
      'Arroz integral com bife',
      'Macarrão à carbonara',
      'Frango assado com legumes',
      'Carne assada com batatas',
      'Risoto de frango',
      'Estrogonofe de carne',
      'Arroz com lentilha',
      'Macarrão ao pesto',
      'Bife acebolado',
      'Frango grelhado',
      'Picadinho de carne',
      'Arroz de forno',
      'Macarrão integral',
      'Carne de panela',
      'Frango ao molho',
      'Bife à parmegiana',
      'Arroz com grão-de-bico',
      'Macarrão com brócolis',
      'Frango empanado',
      'Carne moída com legumes',
      'Risoto de cogumelos',
      'Macarrão ao sugo',
      'Bife grelhado simples',
      'Frango ao curry',
    ],
    'afternoon_snack': [
      'Pipoca com queijo',
      'Pão com pasta de frango',
      'Frutas com granola',
      'Bolo de chocolate',
      'Suco natural',
      'Tapioca de coco ralado',
      'Chips de batata-doce',
      'Pão com geleia',
      'Frutas picadas',
      'Bolo de banana',
      'Vitamina de morango',
      'Biscoitos integrais',
      'Queijo com mel',
      'Pipoca doce',
      'Smoothie de frutas',
      'Bolo de cenoura',
      'Pão de queijo',
      'Frutas com iogurte',
      'Vitamina de banana',
      'Biscoitos de aveia',
      'Tapioca de queijo branco',
      'Chips caseiros',
      'Bolo de fubá',
      'Smoothie verde',
      'Queijo branco',
      'Pipoca salgada',
      'Frutas desidratadas',
      'Bolo caseiro',
      'Vitamina tropical',
      'Biscoitos simples',
    ],
    'dinner': [
      'Sopa de carne com legumes',
      'Omelete caprese',
      'Sanduíche natural de frango',
      'Salada Caesar com frango',
      'Wrap de carne',
      'Pizza de frango com catupiry',
      'Sopa de legumes',
      'Omelete de queijo',
      'Sanduíche integral',
      'Salada completa',
      'Wrap de frango ao curry',
      'Calzone de carne',
      'Sopa de mandioquinha',
      'Omelete de brócolis',
      'Sanduíche de peito de peru',
      'Salada morna',
      'Wrap vegetariano',
      'Pizza caseira',
      'Sopa de lentilha',
      'Omelete simples',
      'Sanduíche leve',
      'Salada de quinoa',
      'Wrap integral',
      'Esfiha de carne',
      'Sopa de feijão',
      'Omelete de tomate',
      'Sanduíche de frango',
      'Salada verde',
      'Wrap de carne moída',
      'Pizza de frigideira',
    ],
    'supper': [
      'Chá com torradas',
      'Iogurte',
      'Frutas cozidas',
      'Leite morno com mel',
      'Gelatina',
      'Castanhas',
      'Chá de camomila',
      'Frutas frescas',
      'Banana assada',
      'Leite com aveia',
      'Gelatina diet',
      'Mix de nuts',
      'Chá verde',
      'Iogurte com mel',
      'Maçã cozida',
      'Leite morno',
      'Gelatina de frutas',
      'Amêndoas',
      'Chá de hortelã',
      'Smoothie leve',
      'Pera assada',
      'Leite com cacau',
      'Gelatina light',
      'Nozes',
      'Chá de erva-doce',
      'Frutas picadas',
      'Banana com canela',
      'Leite simples',
      'Gelatina com coco',
      'Castanhas de caju',
    ],
  },

  // ============= SEM PEIXE (180 itens) =============
  'peixe': {
    'breakfast': [
      'Pão com queijo e presunto',
      'Mingau com frutas secas',
      'Panqueca com frango desfiado',
      'Smoothie de frutas',
      'Tapioca de queijo branco',
      'Omelete com vegetais',
      'Pão integral com requeijão',
      'Mingau de aveia',
      'Panqueca de banana',
      'Smoothie bowl',
      'Crepioca com carne',
      'Omelete de queijo',
      'Pão com geleia',
      'Mingau de quinoa',
      'Panqueca proteica',
      'Smoothie verde',
      'Tapioca de frango desfiado',
      'Wrap de ovo',
      'Pão de queijo',
      'Mingau de fubá',
      'Panqueca integral',
      'Smoothie tropical',
      'Crepioca com presunto',
      'Omelete caprese',
      'Pão com abacate',
      'Mingau de tapioca',
      'Panqueca doce',
      'Smoothie de morango',
      'Tapioca doce',
      'Wrap de frango',
    ],
    'morning_snack': [
      'Frutas frescas',
      'Oleaginosas',
      'Iogurte com granola',
      'Bolo caseiro',
      'Vitamina proteica',
      'Queijo com biscoitos',
      'Maçã com pasta de amendoim',
      'Mix de nuts',
      'Iogurte grego',
      'Bolo de banana',
      'Smoothie de frutas',
      'Biscoitos integrais',
      'Pera com queijo',
      'Castanhas variadas',
      'Vitamina de abacate',
      'Bolo de cenoura',
      'Frutas secas',
      'Amêndoas',
      'Iogurte com mel',
      'Bolo de fubá',
      'Smoothie verde',
      'Biscoitos de aveia',
      'Queijo cottage',
      'Nozes torradas',
      'Vitamina de banana',
      'Bolo de chocolate',
      'Frutas picadas',
      'Castanhas de caju',
      'Iogurte batido',
      'Smoothie tropical',
    ],
    'lunch': [
      'Arroz, feijão, carne bovina e salada',
      'Macarrão com frango ao molho pesto',
      'Bife à parmegiana',
      'Frango assado com legumes',
      'Estrogonofe de carne',
      'Risoto de frango',
      'Arroz integral com bife',
      'Macarrão à bolonhesa',
      'Frango xadrez',
      'Carne assada com batatas',
      'Lasanha de carne',
      'Feijoada',
      'Arroz com lentilha e frango',
      'Macarrão à carbonara',
      'Bife acebolado',
      'Frango grelhado com quinoa',
      'Picadinho de carne',
      'Risoto de cogumelos',
      'Arroz de forno',
      'Macarrão integral com carne',
      'Frango ao curry',
      'Carne de panela',
      'Arroz com grão-de-bico',
      'Macarrão com brócolis e frango',
      'Bife grelhado',
      'Frango empanado',
      'Carne moída com legumes',
      'Risoto de carne',
      'Macarrão ao sugo',
      'Frango ao molho madeira',
    ],
    'afternoon_snack': [
      'Pipoca temperada',
      'Pão com pasta de frango',
      'Frutas com iogurte',
      'Bolo de cenoura',
      'Suco verde',
      'Biscoitos com geleia',
      'Tapioca de queijo branco',
      'Chips de batata-doce',
      'Frutas frescas',
      'Bolo de banana',
      'Vitamina de morango',
      'Biscoitos integrais',
      'Queijo com mel',
      'Pipoca doce',
      'Smoothie de frutas',
      'Bolo de fubá',
      'Pão de queijo',
      'Frutas com granola',
      'Vitamina de abacate',
      'Biscoitos de aveia',
      'Tapioca doce',
      'Chips caseiros',
      'Bolo caseiro',
      'Smoothie verde',
      'Queijo branco',
      'Pipoca salgada',
      'Frutas desidratadas',
      'Bolo de chocolate',
      'Vitamina tropical',
      'Biscoitos simples',
    ],
    'dinner': [
      'Sopa de carne com legumes',
      'Omelete caprese',
      'Sanduíche natural de frango',
      'Salada Caesar com frango',
      'Wrap de carne',
      'Pizza de frango',
      'Sopa de legumes com frango',
      'Omelete de queijo',
      'Sanduíche integral',
      'Salada completa com bife',
      'Wrap de frango grelhado',
      'Calzone de carne',
      'Sopa de mandioquinha',
      'Omelete de brócolis',
      'Sanduíche de peito de peru',
      'Salada morna com frango',
      'Wrap vegetariano',
      'Pizza caseira',
      'Sopa de lentilha',
      'Omelete simples',
      'Sanduíche de frango',
      'Salada de quinoa',
      'Wrap integral',
      'Esfiha de carne',
      'Sopa de feijão',
      'Omelete de tomate',
      'Sanduíche leve',
      'Salada verde com frango',
      'Wrap de carne moída',
      'Pizza de frigideira',
    ],
    'supper': [
      'Chá com torradas',
      'Iogurte',
      'Frutas cozidas',
      'Leite com mel',
      'Gelatina',
      'Castanhas',
      'Chá de camomila',
      'Frutas frescas',
      'Banana assada',
      'Leite morno',
      'Gelatina diet',
      'Mix de nuts',
      'Chá verde',
      'Iogurte com mel',
      'Maçã assada',
      'Leite com aveia',
      'Gelatina de frutas',
      'Amêndoas',
      'Chá de hortelã',
      'Smoothie leve',
      'Pera cozida',
      'Leite com cacau',
      'Gelatina light',
      'Nozes',
      'Chá de erva-doce',
      'Frutas picadas',
      'Banana com canela',
      'Leite simples',
      'Gelatina com coco',
      'Castanhas variadas',
    ],
  },

  // ============= SEM OVOS (180 itens) =============
  'ovos': {
    'breakfast': [
      'Pão com queijo e geleia',
      'Mingau de aveia com frutas',
      'Tapioca de queijo branco',
      'Smoothie de frutas',
      'Pão de queijo',
      'Iogurte com granola',
      'Pão integral com requeijão',
      'Mingau de quinoa',
      'Tapioca com frango',
      'Smoothie bowl',
      'Pão com abacate',
      'Mingau de fubá',
      'Tapioca doce',
      'Smoothie verde',
      'Pão com geleia de morango',
      'Mingau de tapioca',
      'Tapioca de coco ralado',
      'Smoothie tropical',
      'Pão de forma com queijo',
      'Mingau de aveia com banana',
      'Tapioca com presunto',
      'Smoothie de morango',
      'Pão integral com pasta de amendoim',
      'Mingau de chia',
      'Tapioca com carne seca',
      'Smoothie de abacate',
      'Pão com requeijão e tomate',
      'Mingau de amaranto',
      'Tapioca com queijo coalho',
      'Smoothie de manga',
    ],
    'morning_snack': [
      'Frutas variadas',
      'Castanhas e amêndoas',
      'Queijo com biscoitos',
      'Bolo sem ovos de banana e aveia',
      'Vitamina de morango',
      'Hummus com vegetais',
      'Maçã com queijo',
      'Mix de nuts',
      'Iogurte natural',
      'Bolo de milho sem ovos',
      'Smoothie de frutas',
      'Biscoitos sem ovos',
      'Pera com queijo brie',
      'Oleaginosas variadas',
      'Vitamina de abacate',
      'Bolo de cenoura sem ovos',
      'Frutas secas',
      'Castanhas de caju',
      'Iogurte com mel',
      'Bolo de fubá sem ovos',
      'Smoothie verde',
      'Biscoitos de aveia sem ovos',
      'Queijo cottage',
      'Nozes torradas',
      'Vitamina de banana',
      'Bolo vegano',
      'Frutas frescas',
      'Amêndoas',
      'Iogurte grego',
      'Smoothie tropical',
    ],
    'lunch': [
      'Arroz, feijão, carne e salada',
      'Macarrão ao sugo com almôndegas',
      'Frango grelhado com purê',
      'Peixe assado com legumes',
      'Risoto de cogumelos',
      'Carne de panela com batatas',
      'Arroz integral com bife',
      'Macarrão à bolonhesa',
      'Frango xadrez',
      'Salmão grelhado',
      'Risoto de frango',
      'Estrogonofe de carne',
      'Arroz com lentilha',
      'Macarrão ao pesto',
      'Bife acebolado',
      'Frango assado',
      'Peixe ao molho de tomate',
      'Carne moída com legumes',
      'Arroz de forno',
      'Macarrão à carbonara (sem ovo)',
      'Frango ao curry',
      'Tilápia grelhada',
      'Risoto de camarão',
      'Carne assada',
      'Arroz com grão-de-bico',
      'Macarrão com brócolis',
      'Frango grelhado simples',
      'Peixe empanado',
      'Picadinho de carne',
      'Feijoada',
    ],
    'afternoon_snack': [
      'Pipoca natural',
      'Pão com pasta de atum',
      'Frutas com mel',
      'Bolo de milho sem ovos',
      'Suco natural',
      'Biscoitos sem ovos',
      'Tapioca de queijo branco',
      'Chips de batata-doce',
      'Frutas frescas',
      'Bolo de banana sem ovos',
      'Vitamina de morango',
      'Biscoitos veganos',
      'Queijo com geleia',
      'Pipoca doce',
      'Smoothie de frutas',
      'Bolo de cenoura sem ovos',
      'Pão de queijo',
      'Frutas com iogurte',
      'Vitamina de banana',
      'Biscoitos de aveia sem ovos',
      'Tapioca doce',
      'Chips caseiros',
      'Bolo sem ovos',
      'Smoothie verde',
      'Queijo branco',
      'Pipoca salgada',
      'Frutas desidratadas',
      'Bolo vegano',
      'Vitamina tropical',
      'Biscoitos simples',
    ],
    'dinner': [
      'Sopa de legumes com carne',
      'Salada completa com frango',
      'Sanduíche de frango',
      'Wrap de carne com salada',
      'Risoto de frango',
      'Crepe de tapioca recheado',
      'Sopa de mandioquinha',
      'Salada Caesar (sem ovo)',
      'Sanduíche integral',
      'Wrap de frango',
      'Creme de legumes',
      'Tapioca salgada',
      'Sopa de lentilha',
      'Salada morna',
      'Sanduíche natural',
      'Wrap integral',
      'Risoto de cogumelos',
      'Crepe de tapioca com frango',
      'Sopa de feijão',
      'Salada completa',
      'Sanduíche de peito de peru',
      'Wrap vegetariano',
      'Creme de abóbora',
      'Tapioca com carne',
      'Sopa de legumes',
      'Salada de quinoa',
      'Sanduíche leve',
      'Wrap de carne moída',
      'Risoto simples',
      'Crepe de tapioca com queijo',
    ],
    'supper': [
      'Chá com torradas',
      'Iogurte',
      'Frutas cozidas',
      'Leite com mel',
      'Gelatina',
      'Castanhas',
      'Chá de camomila',
      'Frutas frescas',
      'Banana assada',
      'Leite morno',
      'Gelatina diet',
      'Mix de nuts',
      'Chá verde',
      'Iogurte com mel',
      'Maçã assada',
      'Leite com aveia',
      'Gelatina de frutas',
      'Amêndoas',
      'Chá de hortelã',
      'Smoothie leve',
      'Pera cozida',
      'Leite com cacau',
      'Gelatina light',
      'Nozes',
      'Chá de erva-doce',
      'Frutas picadas',
      'Banana com canela',
      'Leite simples',
      'Gelatina com coco',
      'Castanhas variadas',
    ],
  },

  // ============= SEM SOJA (180 itens) =============
  'soja': {
    'breakfast': [
      'Pão integral com queijo',
      'Mingau de aveia com leite',
      'Panqueca com mel',
      'Smoothie de frutas com leite',
      'Tapioca de queijo branco',
      'Omelete com vegetais',
      'Pão com geleia',
      'Mingau de quinoa',
      'Panqueca de banana',
      'Smoothie bowl',
      'Crepioca com frango',
      'Omelete de queijo',
      'Pão de queijo',
      'Mingau de fubá',
      'Panqueca integral',
      'Smoothie verde',
      'Tapioca com frango',
      'Wrap de ovo',
      'Pão com requeijão',
      'Mingau de aveia com frutas',
      'Panqueca proteica',
      'Smoothie tropical',
      'Crepioca com presunto',
      'Omelete caprese',
      'Pão com abacate',
      'Mingau de tapioca',
      'Panqueca doce',
      'Smoothie de morango',
      'Tapioca doce',
      'Wrap de frango',
    ],
    'morning_snack': [
      'Frutas frescas',
      'Castanhas variadas',
      'Queijo com biscoitos',
      'Bolo caseiro',
      'Vitamina com leite',
      'Iogurte com granola',
      'Maçã com queijo',
      'Mix de nuts',
      'Iogurte natural',
      'Bolo de banana',
      'Smoothie de frutas',
      'Biscoitos integrais',
      'Pera com queijo',
      'Oleaginosas',
      'Vitamina de abacate',
      'Bolo de cenoura',
      'Frutas secas',
      'Amêndoas',
      'Iogurte com mel',
      'Bolo de fubá',
      'Smoothie verde',
      'Biscoitos de aveia',
      'Queijo cottage',
      'Nozes',
      'Vitamina de banana',
      'Bolo de chocolate',
      'Frutas picadas',
      'Castanhas de caju',
      'Iogurte grego',
      'Smoothie tropical',
    ],
    'lunch': [
      'Arroz, feijão, carne e salada',
      'Macarrão à bolonhesa',
      'Frango grelhado com legumes',
      'Peixe assado com arroz',
      'Risoto de cogumelos',
      'Carne assada com batatas',
      'Arroz integral com bife',
      'Macarrão ao sugo',
      'Frango xadrez',
      'Salmão grelhado',
      'Risoto de frango',
      'Estrogonofe de carne',
      'Arroz com lentilha',
      'Macarrão ao pesto',
      'Bife acebolado',
      'Frango assado',
      'Peixe ao molho',
      'Carne moída com legumes',
      'Arroz de forno',
      'Macarrão à carbonara',
      'Frango ao curry',
      'Tilápia grelhada',
      'Risoto de camarão',
      'Carne de panela',
      'Arroz com grão-de-bico',
      'Macarrão com brócolis',
      'Frango grelhado simples',
      'Peixe empanado',
      'Picadinho de carne',
      'Feijoada',
    ],
    'afternoon_snack': [
      'Pipoca caseira',
      'Pão com queijo',
      'Frutas com mel',
      'Bolo caseiro',
      'Suco natural',
      'Biscoitos integrais',
      'Tapioca de queijo branco',
      'Chips de batata-doce',
      'Frutas frescas',
      'Bolo de banana',
      'Vitamina com leite',
      'Biscoitos de aveia',
      'Queijo com geleia',
      'Pipoca doce',
      'Smoothie de frutas',
      'Bolo de cenoura',
      'Pão de queijo',
      'Frutas com iogurte',
      'Vitamina de banana',
      'Biscoitos simples',
      'Tapioca doce',
      'Chips caseiros',
      'Bolo de fubá',
      'Smoothie verde',
      'Queijo branco',
      'Pipoca salgada',
      'Frutas desidratadas',
      'Bolo de chocolate',
      'Vitamina tropical',
      'Biscoitos integrais',
    ],
    'dinner': [
      'Sopa de legumes com carne',
      'Omelete caprese',
      'Sanduíche de frango',
      'Salada completa',
      'Wrap de carne',
      'Pizza caseira',
      'Sopa de mandioquinha',
      'Omelete de queijo',
      'Sanduíche integral',
      'Salada Caesar',
      'Wrap de frango',
      'Calzone de carne',
      'Sopa de lentilha',
      'Omelete de brócolis',
      'Sanduíche natural',
      'Salada morna',
      'Wrap integral',
      'Esfiha de carne',
      'Sopa de feijão',
      'Omelete simples',
      'Sanduíche leve',
      'Salada de quinoa',
      'Wrap vegetariano',
      'Pizza de frigideira',
      'Sopa de legumes',
      'Omelete de tomate',
      'Sanduíche de peito de peru',
      'Salada verde',
      'Wrap de carne moída',
      'Crepe recheado',
    ],
    'supper': [
      'Chá com biscoitos',
      'Iogurte',
      'Frutas cozidas',
      'Leite com mel',
      'Gelatina',
      'Castanhas',
      'Chá de camomila',
      'Frutas frescas',
      'Banana assada',
      'Leite morno',
      'Gelatina diet',
      'Mix de nuts',
      'Chá verde',
      'Iogurte com mel',
      'Maçã assada',
      'Leite com aveia',
      'Gelatina de frutas',
      'Amêndoas',
      'Chá de hortelã',
      'Smoothie leve',
      'Pera cozida',
      'Leite com cacau',
      'Gelatina light',
      'Nozes',
      'Chá de erva-doce',
      'Frutas picadas',
      'Banana com canela',
      'Leite simples',
      'Gelatina com coco',
      'Castanhas variadas',
    ],
  },

  // ============= SEM FRUTOSE (180 itens) =============
  'frutose': {
    'breakfast': [
      'Pão integral com queijo',
      'Mingau de aveia simples',
      'Omelete com vegetais',
      'Tapioca de queijo branco',
      'Pão de queijo',
      'Iogurte natural',
      'Panqueca salgada',
      'Crepioca com frango',
      'Pão com requeijão',
      'Mingau de quinoa',
      'Omelete de queijo',
      'Tapioca de carne moída',
      'Wrap de ovo',
      'Pão integral simples',
      'Mingau de fubá',
      'Panqueca de batata',
      'Crepioca com presunto',
      'Pão com queijo branco',
      'Iogurte grego',
      'Omelete caprese',
      'Tapioca simples',
      'Pão de forma',
      'Mingau de aveia com leite',
      'Panqueca integral',
      'Wrap de frango',
      'Pão com manteiga',
      'Mingau de tapioca',
      'Omelete de ervas',
      'Tapioca com ovo',
      'Crepioca simples',
    ],
    'morning_snack': [
      'Iogurte natural',
      'Queijo branco',
      'Castanhas de caju',
      'Ovo cozido',
      'Queijo cottage',
      'Biscoitos de arroz',
      'Palitos de cenoura',
      'Queijo minas',
      'Pepino com homus',
      'Tomate cereja',
      'Azeitonas',
      'Biscoitos de polvilho',
      'Queijo brie',
      'Macadâmia',
      'Iogurte grego',
      'Torradas integrais',
      'Nozes',
      'Queijo prato',
      'Amêndoas',
      'Cream cheese com pepino',
      'Queijo coalho',
      'Biscoitos cream cracker',
      'Queijo provolone',
      'Castanhas do Pará',
      'Iogurte batido',
      'Queijo cottage com ervas',
      'Biscoitos de água e sal',
      'Queijo gorgonzola',
      'Mix de castanhas',
      'Queijo mussarela',
    ],
    'lunch': [
      'Arroz com feijão e bife grelhado',
      'Frango assado com batata e legumes',
      'Macarrão ao sugo com carne moída',
      'Peixe grelhado com arroz integral',
      'Risoto de cogumelos',
      'Carne de panela com mandioca',
      'Arroz integral com lentilha e omelete',
      'Filé mignon com purê de batata',
      'Frango xadrez com arroz',
      'Tilápia com legumes no vapor',
      'Macarrão à carbonara',
      'Bife acebolado com arroz e feijão',
      'Frango grelhado com quinoa',
      'Salmão com brócolis',
      'Risoto de frango',
      'Estrogonofe de carne',
      'Arroz com grão-de-bico e frango',
      'Macarrão com brócolis',
      'Carne assada com batatas',
      'Frango ao molho branco',
      'Peixe ao forno com legumes',
      'Arroz de couve-flor com carne',
      'Frango empanado com salada',
      'Macarrão integral com frango',
      'Bife à parmegiana',
      'Risoto de camarão',
      'Carne moída com purê',
      'Frango ao curry com arroz',
      'Lasanha de carne',
      'Feijoada light',
    ],
    'afternoon_snack': [
      'Pipoca caseira',
      'Pão de queijo',
      'Tapioca de queijo branco',
      'Biscoitos de polvilho',
      'Iogurte natural',
      'Queijo branco',
      'Torradas com requeijão',
      'Chips de batata-doce',
      'Biscoitos de arroz',
      'Queijo minas com presunto',
      'Tapioca salgada',
      'Iogurte grego',
      'Pão integral com queijo',
      'Biscoitos cream cracker',
      'Queijo cottage',
      'Tapioca de coco ralado',
      'Iogurte batido',
      'Pão com pasta de atum',
      'Biscoitos de água e sal',
      'Queijo coalho grelhado',
      'Tapioca com frango',
      'Iogurte com aveia',
      'Pão de forma com presunto',
      'Biscoitos integrais',
      'Queijo prato',
      'Tapioca simples',
      'Iogurte com granola',
      'Pão com requeijão',
      'Biscoitos de polvilho doce',
      'Queijo mussarela',
    ],
    'dinner': [
      'Omelete de queijo com salada',
      'Sopa de legumes com carne',
      'Wrap de frango com vegetais',
      'Salada completa com ovo cozido',
      'Risoto de cogumelos',
      'Creme de legumes',
      'Omelete de brócolis',
      'Sopa de mandioquinha',
      'Wrap de carne',
      'Salada Caesar',
      'Creme de abóbora',
      'Omelete caprese',
      'Sopa de lentilha',
      'Wrap integral',
      'Salada morna com frango',
      'Creme de brócolis',
      'Omelete simples',
      'Sopa de feijão branco',
      'Wrap de atum',
      'Salada de quinoa',
      'Creme de mandioquinha',
      'Omelete de cogumelos',
      'Sopa de batata',
      'Wrap de frango ao curry',
      'Salada verde com grelhados',
      'Creme de espinafre',
      'Omelete de tomate',
      'Sopa de grão-de-bico',
      'Wrap vegetariano',
      'Salada completa',
    ],
    'supper': [
      'Chá de camomila',
      'Iogurte natural',
      'Queijo branco',
      'Leite morno',
      'Gelatina diet',
      'Castanhas (pequena porção)',
      'Chá de erva-doce',
      'Iogurte grego',
      'Queijo cottage',
      'Leite com aveia',
      'Gelatina',
      'Amêndoas',
      'Chá de hortelã',
      'Iogurte batido',
      'Queijo minas',
      'Leite morno com canela',
      'Gelatina de limão',
      'Nozes',
      'Chá verde',
      'Iogurte com aveia',
      'Queijo coalho',
      'Leite simples',
      'Gelatina light',
      'Castanhas de caju',
      'Chá de ervas',
      'Iogurte com chia',
      'Queijo prato',
      'Leite com mel',
      'Gelatina com coco',
      'Macadâmia',
    ],
  },

  // ============= SEM FODMAP (180 itens) =============
  'fodmap': {
    'breakfast': [
      'Tapioca de queijo branco com ovo mexido',
      'Pão sem glúten com manteiga',
      'Mingau de aveia sem glúten com banana',
      'Omelete de espinafre com queijo',
      'Panqueca de banana sem trigo',
      'Smoothie de morango com leite sem lactose',
      'Crepioca com frango desfiado',
      'Pão de queijo caseiro',
      'Torrada sem glúten com abacate',
      'Vitamina de banana com leite de coco',
      'Omelete simples com tomate',
      'Tapioca com queijo coalho',
      'Mingau de quinoa com canela',
      'Panqueca de batata-doce',
      'Smoothie de mirtilo',
      'Crepioca com presunto',
      'Pão sem glúten com geleia',
      'Omelete de abobrinha',
      'Tapioca doce com coco',
      'Vitamina de kiwi',
      'Panqueca sem glúten',
      'Mingau de arroz',
      'Crepioca simples',
      'Torrada sem glúten com queijo',
      'Omelete de cenoura',
      'Tapioca com atum',
      'Smoothie de mamão',
      'Pão de queijo com requeijão',
      'Vitamina de morango',
      'Panqueca proteica sem trigo',
    ],
    'morning_snack': [
      'Banana madura',
      'Uvas (pequena porção)',
      'Queijo branco',
      'Castanhas de caju',
      'Iogurte sem lactose',
      'Morangos frescos',
      'Queijo cottage',
      'Nozes',
      'Kiwi',
      'Queijo minas',
      'Mirtilos',
      'Amêndoas',
      'Mamão',
      'Queijo brie',
      'Laranja',
      'Macadâmia',
      'Tangerina',
      'Queijo prato',
      'Melão',
      'Castanhas do Pará',
      'Abacaxi (pequena porção)',
      'Queijo coalho',
      'Maracujá',
      'Biscoitos de arroz',
      'Carambola',
      'Queijo mussarela',
      'Limão siciliano',
      'Biscoitos de polvilho',
      'Pitaya',
      'Queijo provolone',
    ],
    'lunch': [
      'Arroz com frango grelhado e cenoura',
      'Bife de contrafilé com batata e espinafre',
      'Peixe assado com arroz e abobrinha',
      'Risoto de cenoura com frango',
      'Carne de panela com batata-doce',
      'Frango xadrez sem cebola com arroz',
      'Salmão grelhado com quinoa',
      'Tilápia com legumes (cenoura, abobrinha)',
      'Macarrão de arroz com molho de tomate caseiro',
      'Bife acebolado (cebolinha verde apenas) com arroz',
      'Frango ao limão com batata',
      'Risoto de abóbora',
      'Carne assada com mandioca',
      'Frango grelhado com purê de batata-doce',
      'Peixe ao forno com ervas',
      'Arroz integral com lentilha (pequena porção)',
      'Bife grelhado com salada verde',
      'Frango empanado sem glúten',
      'Risoto de cogumelos (sem alho)',
      'Carne moída com abobrinha',
      'Tilápia com arroz basmati',
      'Frango ao curry (sem cebola)',
      'Salmão com aspargos',
      'Bife à milanesa sem glúten',
      'Risoto de frango',
      'Carne de sol com mandioca',
      'Frango assado com batata rústica',
      'Peixe grelhado simples',
      'Arroz de couve-flor com carne',
      'Frango ao molho de ervas',
    ],
    'afternoon_snack': [
      'Pipoca caseira',
      'Tapioca de queijo branco',
      'Banana com pasta de amendoim',
      'Pão de queijo',
      'Iogurte sem lactose',
      'Biscoitos de arroz',
      'Queijo branco com presunto',
      'Tapioca doce',
      'Chips de batata-doce',
      'Morangos com creme',
      'Biscoitos de polvilho',
      'Queijo minas',
      'Tapioca de coco ralado',
      'Frutas vermelhas',
      'Biscoitos sem glúten',
      'Queijo coalho grelhado',
      'Tapioca simples',
      'Kiwi',
      'Biscoitos de arroz com geleia',
      'Queijo prato',
      'Tapioca com frango',
      'Mamão',
      'Biscoitos de polvilho doce',
      'Queijo cottage',
      'Tapioca com atum',
      'Uvas',
      'Pão sem glúten',
      'Queijo brie',
      'Tapioca com presunto',
      'Tangerina',
    ],
    'dinner': [
      'Omelete de espinafre com queijo',
      'Sopa de cenoura com gengibre',
      'Salada completa com frango',
      'Wrap de alface com carne',
      'Creme de abóbora',
      'Omelete de abobrinha',
      'Sopa de batata-doce',
      'Salada verde com salmão',
      'Wrap de alface com atum',
      'Creme de cenoura',
      'Omelete simples',
      'Sopa de mandioquinha',
      'Salada morna com frango',
      'Wrap de alface com frango',
      'Creme de espinafre',
      'Omelete de tomate',
      'Sopa de abobrinha',
      'Salada de folhas com ovo',
      'Wrap de alface com camarão',
      'Creme de batata-doce',
      'Omelete caprese',
      'Sopa cremosa de abóbora',
      'Salada Caesar adaptada',
      'Wrap de alface com presunto',
      'Creme de mandioca',
      'Omelete de ervas',
      'Sopa de legumes (sem cebola/alho)',
      'Salada de quinoa',
      'Wrap de alface simples',
      'Creme de brócolis (pequena porção)',
    ],
    'supper': [
      'Chá de gengibre',
      'Iogurte sem lactose',
      'Banana madura',
      'Leite sem lactose morno',
      'Gelatina',
      'Castanhas de caju',
      'Chá de hortelã',
      'Morangos',
      'Queijo branco',
      'Leite de coco morno',
      'Gelatina diet',
      'Nozes',
      'Chá verde',
      'Kiwi',
      'Queijo cottage',
      'Leite de amêndoas',
      'Gelatina de morango',
      'Amêndoas',
      'Chá de camomila',
      'Mamão',
      'Queijo minas',
      'Leite de arroz',
      'Gelatina light',
      'Macadâmia',
      'Chá de erva-doce',
      'Tangerina',
      'Queijo coalho',
      'Leite morno simples',
      'Gelatina com frutas',
      'Castanhas do Pará',
    ],
  },

  // ============= SEM HISTAMINA (180 itens) =============
  'histamina': {
    'breakfast': [
      'Pão fresco com manteiga e geleia caseira',
      'Mingau de aveia com maçã fresca',
      'Omelete de legumes frescos (abobrinha, cenoura)',
      'Tapioca com queijo fresco (ricota)',
      'Panqueca de banana com mel',
      'Smoothie de maçã com leite fresco',
      'Crepioca com frango fresco',
      'Pão de queijo fresco',
      'Torrada com ricota e pepino',
      'Vitamina de pera com aveia',
      'Omelete simples com ervas frescas',
      'Tapioca com queijo cottage',
      'Mingau de quinoa com frutas frescas',
      'Panqueca de batata-doce',
      'Smoothie de melão',
      'Crepioca com peito de peru fresco',
      'Pão fresco com geleia',
      'Omelete de abobrinha',
      'Tapioca doce com coco fresco',
      'Vitamina de maçã',
      'Panqueca integral',
      'Mingau de tapioca',
      'Crepioca simples',
      'Torrada com queijo fresco',
      'Omelete de cenoura',
      'Tapioca com frango',
      'Smoothie de pepino',
      'Pão com manteiga',
      'Vitamina de melancia',
      'Panqueca proteica',
    ],
    'morning_snack': [
      'Maçã fresca',
      'Pera',
      'Melão',
      'Melancia',
      'Queijo fresco (ricota)',
      'Pepino',
      'Cenoura baby',
      'Queijo cottage',
      'Uvas frescas',
      'Biscoitos caseiros frescos',
      'Manga fresca',
      'Queijo minas fresco',
      'Coco fresco',
      'Biscoitos de arroz',
      'Mamão',
      'Queijo branco fresco',
      'Romã',
      'Biscoitos de polvilho',
      'Caqui',
      'Ricota com mel',
      'Pitaya',
      'Biscoitos integrais frescos',
      'Lichia',
      'Queijo coalho fresco',
      'Carambola',
      'Biscoitos caseiros',
      'Mirtilo fresco',
      'Queijo prato fresco',
      'Kiwi amarelo',
      'Biscoitos de água e sal',
    ],
    'lunch': [
      'Arroz com frango fresco grelhado e salada',
      'Bife fresco com batata e legumes',
      'Peixe fresco grelhado com arroz',
      'Risoto de legumes frescos',
      'Carne fresca de panela com mandioca',
      'Frango fresco assado com batata-doce',
      'Filé de peixe fresco com quinoa',
      'Tilápia fresca com legumes',
      'Macarrão fresco com azeite e ervas',
      'Bife fresco acebolado com arroz',
      'Frango fresco grelhado com purê',
      'Risoto de abobrinha',
      'Carne fresca assada com batatas',
      'Frango fresco ao limão',
      'Peixe fresco ao forno',
      'Arroz integral com frango fresco',
      'Bife fresco grelhado simples',
      'Frango fresco empanado',
      'Risoto de cenoura',
      'Carne fresca moída com legumes',
      'Tilápia fresca simples',
      'Frango fresco ao molho de ervas',
      'Peixe fresco com brócolis',
      'Bife fresco à milanesa',
      'Risoto de frango fresco',
      'Carne fresca de sol',
      'Frango fresco com mandioca',
      'Peixe fresco grelhado simples',
      'Arroz com lentilha e frango fresco',
      'Frango fresco xadrez',
    ],
    'afternoon_snack': [
      'Pipoca caseira fresca',
      'Pão de queijo fresco',
      'Tapioca com queijo fresco',
      'Biscoitos caseiros',
      'Iogurte fresco',
      'Frutas frescas variadas',
      'Queijo cottage com mel',
      'Tapioca doce',
      'Chips de batata-doce caseiro',
      'Melão picado',
      'Biscoitos de arroz',
      'Queijo minas fresco',
      'Tapioca de coco ralado',
      'Maçã fresca',
      'Biscoitos de polvilho',
      'Ricota com geleia',
      'Tapioca simples',
      'Pera fresca',
      'Biscoitos integrais',
      'Queijo branco fresco',
      'Tapioca com frango',
      'Melancia',
      'Pão fresco com manteiga',
      'Queijo coalho fresco',
      'Tapioca com presunto fresco',
      'Manga fresca',
      'Biscoitos caseiros simples',
      'Queijo prato fresco',
      'Tapioca com ovo',
      'Frutas da estação',
    ],
    'dinner': [
      'Omelete de legumes frescos',
      'Sopa caseira de legumes',
      'Salada fresca com frango grelhado',
      'Wrap de alface com carne fresca',
      'Creme de abóbora fresco',
      'Omelete simples com ervas',
      'Sopa de batata fresca',
      'Salada verde com peixe fresco',
      'Wrap de alface com frango',
      'Creme de cenoura',
      'Omelete de abobrinha',
      'Sopa de mandioquinha',
      'Salada morna com frango fresco',
      'Wrap de alface com ovo',
      'Creme de espinafre',
      'Omelete de ervas frescas',
      'Sopa de legumes frescos',
      'Salada completa',
      'Wrap de alface simples',
      'Creme de batata',
      'Omelete de cenoura',
      'Sopa de abobrinha',
      'Salada de folhas frescas',
      'Wrap de alface com ricota',
      'Creme de mandioquinha',
      'Omelete caprese (sem tomate curado)',
      'Sopa cremosa de legumes',
      'Salada de quinoa fresca',
      'Wrap de alface com peito de peru',
      'Creme de brócolis',
    ],
    'supper': [
      'Chá de camomila',
      'Leite fresco morno',
      'Maçã assada',
      'Queijo fresco com mel',
      'Gelatina caseira',
      'Pera cozida',
      'Chá de erva-doce',
      'Leite com aveia',
      'Melão picado',
      'Ricota com mel',
      'Gelatina light',
      'Chá de hortelã',
      'Leite morno simples',
      'Frutas frescas',
      'Queijo cottage',
      'Gelatina de frutas',
      'Chá de ervas',
      'Leite com mel',
      'Manga fresca',
      'Queijo minas fresco',
      'Gelatina diet',
      'Chá verde fresco',
      'Leite de arroz',
      'Melancia',
      'Queijo branco',
      'Gelatina com frutas',
      'Chá de gengibre',
      'Leite de coco',
      'Frutas da estação',
      'Biscoitos caseiros',
    ],
  },

  // ============= SEM CAFEÍNA (180 itens) =============
  'cafeina': {
    'breakfast': [
      'Pão integral com geleia e manteiga',
      'Mingau de aveia com frutas',
      'Panqueca com mel e banana',
      'Smoothie de frutas vermelhas',
      'Tapioca com queijo e presunto',
      'Omelete de vegetais',
      'Pão de queijo com requeijão',
      'Torrada com abacate e ovo',
      'Vitamina de mamão com aveia',
      'Crepioca com frango',
      'Iogurte com granola e frutas',
      'Pão com queijo branco',
      'Mingau de quinoa',
      'Panqueca de banana',
      'Smoothie de manga',
      'Tapioca doce com coco',
      'Omelete caprese',
      'Pão integral com pasta de amendoim',
      'Vitamina de abacate',
      'Crepioca com presunto',
      'Iogurte grego com mel',
      'Pão de forma com ovo',
      'Mingau de tapioca',
      'Panqueca proteica',
      'Smoothie verde',
      'Tapioca com atum',
      'Omelete simples',
      'Pão com geleia',
      'Vitamina de morango',
      'Crepioca simples',
    ],
    'morning_snack': [
      'Frutas variadas',
      'Mix de castanhas',
      'Iogurte natural',
      'Queijo branco',
      'Vitamina de frutas',
      'Biscoitos integrais',
      'Maçã com queijo',
      'Nozes',
      'Iogurte grego',
      'Queijo cottage',
      'Smoothie de frutas',
      'Biscoitos de aveia',
      'Pera',
      'Amêndoas',
      'Vitamina de banana',
      'Queijo minas',
      'Frutas secas',
      'Castanhas de caju',
      'Iogurte batido',
      'Queijo brie',
      'Smoothie tropical',
      'Biscoitos de arroz',
      'Banana',
      'Macadâmia',
      'Vitamina de mamão',
      'Queijo prato',
      'Frutas picadas',
      'Castanhas do Pará',
      'Iogurte com mel',
      'Queijo coalho',
    ],
    'lunch': [
      'Arroz com feijão, carne e salada',
      'Macarrão à bolonhesa',
      'Frango grelhado com legumes',
      'Peixe assado com arroz',
      'Risoto de cogumelos',
      'Carne de panela com batatas',
      'Arroz integral com bife',
      'Macarrão ao sugo',
      'Frango xadrez',
      'Salmão com quinoa',
      'Risoto de frango',
      'Estrogonofe de carne',
      'Arroz com lentilha',
      'Macarrão ao pesto',
      'Bife acebolado',
      'Frango assado',
      'Peixe grelhado',
      'Carne moída com legumes',
      'Arroz de forno',
      'Macarrão à carbonara',
      'Frango ao curry',
      'Tilápia grelhada',
      'Risoto de camarão',
      'Carne assada',
      'Arroz com grão-de-bico',
      'Macarrão com brócolis',
      'Frango empanado',
      'Peixe ao molho',
      'Picadinho de carne',
      'Feijoada',
    ],
    'afternoon_snack': [
      'Pipoca caseira',
      'Pão de queijo',
      'Frutas com mel',
      'Bolo de cenoura',
      'Suco de laranja',
      'Biscoitos integrais',
      'Tapioca de queijo branco',
      'Iogurte com granola',
      'Chips de batata-doce',
      'Bolo de banana',
      'Vitamina de morango',
      'Biscoitos de aveia',
      'Queijo com geleia',
      'Pipoca doce',
      'Smoothie de frutas',
      'Bolo de fubá',
      'Pão com geleia',
      'Frutas frescas',
      'Vitamina de banana',
      'Biscoitos simples',
      'Tapioca doce',
      'Frutas com iogurte',
      'Bolo caseiro',
      'Smoothie tropical',
      'Queijo branco',
      'Pipoca salgada',
      'Frutas desidratadas',
      'Bolo de milho',
      'Vitamina de manga',
      'Biscoitos de arroz',
    ],
    'dinner': [
      'Sopa de legumes com carne',
      'Omelete caprese',
      'Sanduíche de frango',
      'Salada completa',
      'Wrap de carne',
      'Pizza caseira',
      'Sopa de mandioquinha',
      'Omelete de queijo',
      'Sanduíche integral',
      'Salada Caesar',
      'Wrap de frango',
      'Calzone de carne',
      'Sopa de lentilha',
      'Omelete de brócolis',
      'Sanduíche natural',
      'Salada morna',
      'Wrap integral',
      'Esfiha de carne',
      'Sopa de feijão',
      'Omelete simples',
      'Sanduíche leve',
      'Salada de quinoa',
      'Wrap vegetariano',
      'Pizza de frigideira',
      'Sopa de legumes',
      'Omelete de tomate',
      'Sanduíche de peito de peru',
      'Salada verde',
      'Wrap de carne moída',
      'Crepe recheado',
    ],
    'supper': [
      'Leite morno com mel',
      'Iogurte natural',
      'Frutas cozidas',
      'Gelatina',
      'Castanhas',
      'Leite com aveia',
      'Frutas frescas',
      'Banana assada',
      'Gelatina diet',
      'Mix de nuts',
      'Leite de amêndoas',
      'Iogurte com mel',
      'Maçã assada',
      'Gelatina de frutas',
      'Amêndoas',
      'Leite morno simples',
      'Smoothie leve',
      'Pera cozida',
      'Gelatina light',
      'Nozes',
      'Leite de coco',
      'Frutas picadas',
      'Banana com canela',
      'Gelatina com coco',
      'Castanhas de caju',
      'Leite de arroz',
      'Iogurte batido',
      'Frutas da estação',
      'Gelatina com frutas',
      'Macadâmia',
    ],
  },

  // ============= SEM SULFITOS (180 itens) =============
  'sulfitos': {
    'breakfast': [
      'Pão integral caseiro com manteiga',
      'Mingau de aveia com frutas frescas',
      'Omelete de legumes frescos',
      'Tapioca com queijo fresco',
      'Panqueca caseira com mel puro',
      'Smoothie de frutas frescas',
      'Crepioca com frango',
      'Pão de queijo caseiro',
      'Torrada com abacate fresco',
      'Vitamina de banana',
      'Omelete simples',
      'Tapioca com queijo coalho',
      'Mingau de quinoa',
      'Panqueca de banana',
      'Smoothie verde',
      'Crepioca com presunto fresco',
      'Pão caseiro com geleia caseira',
      'Omelete de abobrinha',
      'Tapioca doce',
      'Vitamina de mamão',
      'Panqueca proteica',
      'Mingau de tapioca',
      'Crepioca simples',
      'Torrada com queijo fresco',
      'Omelete de ervas frescas',
      'Tapioca com atum fresco',
      'Smoothie de morango fresco',
      'Pão integral com pasta de amendoim natural',
      'Vitamina de abacate',
      'Panqueca integral',
    ],
    'morning_snack': [
      'Frutas frescas variadas',
      'Castanhas naturais',
      'Iogurte natural sem conservantes',
      'Queijo branco fresco',
      'Vitamina de frutas frescas',
      'Biscoitos caseiros',
      'Maçã fresca',
      'Nozes naturais',
      'Iogurte grego natural',
      'Queijo cottage',
      'Smoothie de frutas frescas',
      'Biscoitos de aveia caseiros',
      'Pera fresca',
      'Amêndoas naturais',
      'Vitamina de banana',
      'Queijo minas fresco',
      'Banana fresca',
      'Castanhas de caju naturais',
      'Iogurte batido natural',
      'Queijo brie',
      'Smoothie tropical fresco',
      'Biscoitos de arroz',
      'Uvas frescas',
      'Macadâmia',
      'Vitamina de mamão',
      'Queijo prato',
      'Melão fresco',
      'Castanhas do Pará',
      'Iogurte com mel puro',
      'Queijo coalho',
    ],
    'lunch': [
      'Arroz com feijão fresco e carne grelhada',
      'Frango grelhado com legumes frescos',
      'Peixe fresco grelhado com arroz',
      'Risoto caseiro de cogumelos frescos',
      'Carne de panela caseira',
      'Arroz integral com bife grelhado',
      'Frango assado com batatas',
      'Tilápia fresca com quinoa',
      'Macarrão caseiro com molho de tomate fresco',
      'Bife acebolado com arroz',
      'Frango xadrez com legumes frescos',
      'Salmão fresco grelhado',
      'Risoto de frango caseiro',
      'Carne assada com mandioca',
      'Frango grelhado com purê caseiro',
      'Peixe ao forno com ervas frescas',
      'Arroz com lentilha e frango',
      'Bife grelhado simples',
      'Frango empanado caseiro',
      'Risoto de camarão fresco',
      'Carne moída com legumes',
      'Tilápia com legumes frescos',
      'Frango ao limão',
      'Salmão com brócolis',
      'Bife à milanesa caseira',
      'Risoto de legumes',
      'Carne de sol com mandioca',
      'Frango com batata-doce',
      'Peixe grelhado simples',
      'Arroz de couve-flor com carne',
    ],
    'afternoon_snack': [
      'Pipoca caseira natural',
      'Pão de queijo caseiro',
      'Frutas frescas com mel',
      'Bolo caseiro de cenoura',
      'Suco de laranja natural fresco',
      'Biscoitos caseiros',
      'Tapioca com queijo fresco',
      'Iogurte natural com granola caseira',
      'Chips de batata-doce caseiro',
      'Bolo de banana caseiro',
      'Vitamina de morango fresco',
      'Biscoitos de aveia caseiros',
      'Queijo fresco com mel',
      'Pipoca doce caseira',
      'Smoothie de frutas frescas',
      'Bolo de fubá caseiro',
      'Pão caseiro com geleia',
      'Frutas frescas variadas',
      'Vitamina de banana',
      'Biscoitos integrais caseiros',
      'Tapioca doce',
      'Frutas com iogurte natural',
      'Bolo caseiro simples',
      'Smoothie tropical',
      'Queijo branco fresco',
      'Pipoca salgada natural',
      'Frutas da estação',
      'Bolo de milho caseiro',
      'Vitamina de manga',
      'Biscoitos de arroz',
    ],
    'dinner': [
      'Sopa caseira de legumes',
      'Omelete de legumes frescos',
      'Sanduíche caseiro de frango',
      'Salada fresca completa',
      'Wrap de alface com carne',
      'Creme caseiro de abóbora',
      'Omelete simples',
      'Sopa de mandioquinha caseira',
      'Salada verde com frango',
      'Wrap de alface com frango',
      'Creme de cenoura caseiro',
      'Omelete de brócolis',
      'Sopa de lentilha caseira',
      'Salada morna com frango',
      'Wrap de alface com ovo',
      'Creme de espinafre',
      'Omelete de ervas',
      'Sopa de batata caseira',
      'Salada Caesar caseira',
      'Wrap de alface simples',
      'Creme de mandioquinha',
      'Omelete caprese',
      'Sopa de legumes frescos',
      'Salada de quinoa',
      'Wrap de alface com presunto',
      'Creme de brócolis',
      'Omelete de tomate',
      'Sopa de abobrinha',
      'Salada de folhas frescas',
      'Wrap de alface com atum',
    ],
    'supper': [
      'Chá de camomila',
      'Leite morno com mel puro',
      'Frutas frescas cozidas',
      'Iogurte natural',
      'Gelatina caseira',
      'Castanhas naturais',
      'Chá de erva-doce',
      'Leite com aveia',
      'Maçã assada',
      'Queijo cottage',
      'Gelatina diet',
      'Nozes naturais',
      'Chá de hortelã',
      'Leite morno simples',
      'Banana cozida',
      'Queijo fresco',
      'Gelatina de frutas',
      'Amêndoas naturais',
      'Chá verde',
      'Smoothie leve',
      'Pera cozida',
      'Ricota com mel',
      'Gelatina light',
      'Macadâmia',
      'Chá de ervas',
      'Frutas picadas',
      'Banana com canela',
      'Leite de coco',
      'Gelatina com frutas',
      'Castanhas de caju',
    ],
  },

  // ============= SEM SORBITOL (180 itens) =============
  'sorbitol': {
    'breakfast': [
      'Pão integral com manteiga e geleia de morango',
      'Mingau de aveia com banana',
      'Omelete de vegetais',
      'Tapioca de queijo branco',
      'Panqueca com mel',
      'Smoothie de banana com leite',
      'Crepioca com frango',
      'Pão de queijo',
      'Torrada com abacate',
      'Vitamina de banana',
      'Omelete simples',
      'Tapioca com queijo coalho',
      'Mingau de quinoa',
      'Panqueca de banana',
      'Smoothie de manga',
      'Crepioca com presunto',
      'Pão com geleia',
      'Omelete de abobrinha',
      'Tapioca doce',
      'Vitamina de mamão',
      'Panqueca proteica',
      'Mingau de tapioca',
      'Crepioca simples',
      'Torrada com queijo',
      'Omelete de ervas',
      'Tapioca com atum',
      'Smoothie de morango',
      'Pão integral com pasta de amendoim',
      'Vitamina de abacate',
      'Panqueca integral',
    ],
    'morning_snack': [
      'Banana madura',
      'Uvas',
      'Manga',
      'Melão',
      'Queijo branco',
      'Mamão',
      'Abacaxi',
      'Queijo cottage',
      'Laranja',
      'Biscoitos de arroz',
      'Tangerina',
      'Queijo minas',
      'Kiwi',
      'Biscoitos de polvilho',
      'Melancia',
      'Queijo brie',
      'Maracujá',
      'Biscoitos integrais',
      'Limão siciliano',
      'Queijo prato',
      'Coco fresco',
      'Biscoitos caseiros',
      'Morango',
      'Queijo coalho',
      'Frutas tropicais',
      'Biscoitos de água e sal',
      'Pitaya',
      'Queijo mussarela',
      'Lichia',
      'Biscoitos cream cracker',
    ],
    'lunch': [
      'Arroz com feijão e frango grelhado',
      'Bife de contrafilé com batata',
      'Peixe grelhado com arroz',
      'Risoto de cogumelos',
      'Carne de panela',
      'Arroz integral com bife',
      'Frango xadrez',
      'Salmão com quinoa',
      'Macarrão ao sugo',
      'Bife acebolado',
      'Frango assado com batatas',
      'Risoto de frango',
      'Carne assada',
      'Frango grelhado com purê',
      'Peixe ao forno',
      'Arroz com lentilha',
      'Bife grelhado',
      'Frango empanado',
      'Risoto de camarão',
      'Carne moída com legumes',
      'Tilápia grelhada',
      'Frango ao curry',
      'Salmão com legumes',
      'Bife à milanesa',
      'Risoto de legumes',
      'Carne de sol',
      'Frango com mandioca',
      'Peixe grelhado simples',
      'Arroz de couve-flor',
      'Frango ao limão',
    ],
    'afternoon_snack': [
      'Pipoca caseira',
      'Pão de queijo',
      'Frutas tropicais',
      'Bolo de cenoura',
      'Suco de laranja',
      'Biscoitos integrais',
      'Tapioca de queijo branco',
      'Iogurte com granola',
      'Chips de batata-doce',
      'Bolo de banana',
      'Vitamina de manga',
      'Biscoitos de aveia',
      'Queijo com mel',
      'Pipoca doce',
      'Smoothie de morango',
      'Bolo de fubá',
      'Pão com geleia',
      'Frutas frescas',
      'Vitamina de banana',
      'Biscoitos simples',
      'Tapioca doce',
      'Frutas com iogurte',
      'Bolo caseiro',
      'Smoothie tropical',
      'Queijo branco',
      'Pipoca salgada',
      'Uvas',
      'Bolo de milho',
      'Vitamina de mamão',
      'Biscoitos de arroz',
    ],
    'dinner': [
      'Sopa de legumes com carne',
      'Omelete caprese',
      'Sanduíche de frango',
      'Salada completa',
      'Wrap de carne',
      'Pizza caseira',
      'Sopa de mandioquinha',
      'Omelete de queijo',
      'Sanduíche integral',
      'Salada Caesar',
      'Wrap de frango',
      'Creme de abóbora',
      'Sopa de lentilha',
      'Omelete de brócolis',
      'Sanduíche natural',
      'Salada morna',
      'Wrap integral',
      'Creme de cenoura',
      'Sopa de feijão',
      'Omelete simples',
      'Sanduíche leve',
      'Salada de quinoa',
      'Wrap vegetariano',
      'Creme de espinafre',
      'Sopa de batata',
      'Omelete de tomate',
      'Sanduíche de peito de peru',
      'Salada verde',
      'Wrap de atum',
      'Creme de mandioquinha',
    ],
    'supper': [
      'Chá de camomila',
      'Iogurte natural',
      'Banana cozida',
      'Leite morno',
      'Gelatina',
      'Castanhas',
      'Chá de erva-doce',
      'Frutas tropicais',
      'Queijo cottage',
      'Leite com mel',
      'Gelatina diet',
      'Nozes',
      'Chá de hortelã',
      'Manga',
      'Queijo branco',
      'Leite de coco',
      'Gelatina de frutas',
      'Amêndoas',
      'Chá verde',
      'Melão',
      'Queijo minas',
      'Leite de amêndoas',
      'Gelatina light',
      'Macadâmia',
      'Chá de ervas',
      'Uvas',
      'Queijo coalho',
      'Leite simples',
      'Gelatina com frutas',
      'Castanhas de caju',
    ],
  },

  // ============= SEM SALICILATOS (180 itens) =============
  'salicilatos': {
    'breakfast': [
      'Pão branco com manteiga',
      'Mingau de aveia com banana',
      'Omelete simples com queijo',
      'Tapioca com queijo branco',
      'Panqueca com mel',
      'Vitamina de banana com leite',
      'Crepioca com frango',
      'Pão de queijo',
      'Torrada com queijo',
      'Leite com aveia',
      'Omelete de abobrinha',
      'Tapioca com requeijão',
      'Mingau de arroz',
      'Panqueca de banana',
      'Vitamina de mamão',
      'Crepioca com presunto',
      'Pão com geleia de pera',
      'Omelete de queijo',
      'Tapioca doce',
      'Leite com mel',
      'Panqueca proteica',
      'Mingau de tapioca',
      'Crepioca simples',
      'Torrada com manteiga',
      'Omelete simples',
      'Tapioca com ovo',
      'Vitamina de pera',
      'Pão integral simples',
      'Leite com banana',
      'Panqueca simples',
    ],
    'morning_snack': [
      'Banana madura',
      'Pera',
      'Mamão',
      'Melão',
      'Queijo branco',
      'Coco fresco',
      'Manga madura',
      'Queijo cottage',
      'Castanha de caju',
      'Biscoitos simples',
      'Leite',
      'Queijo minas',
      'Nozes',
      'Biscoitos de água e sal',
      'Iogurte natural',
      'Queijo brie',
      'Amêndoas',
      'Biscoitos cream cracker',
      'Vitamina de banana',
      'Queijo prato',
      'Macadâmia',
      'Biscoitos integrais',
      'Leite de coco',
      'Queijo coalho',
      'Castanhas do Pará',
      'Biscoitos de arroz',
      'Iogurte grego',
      'Queijo mussarela',
      'Coco ralado',
      'Biscoitos de polvilho',
    ],
    'lunch': [
      'Arroz branco com frango grelhado',
      'Bife de carne com batata',
      'Peixe grelhado com arroz',
      'Risoto simples de frango',
      'Carne de panela com mandioca',
      'Arroz integral com bife',
      'Frango assado com batatas',
      'Tilápia com legumes simples',
      'Macarrão com manteiga',
      'Bife acebolado com arroz',
      'Frango grelhado com purê',
      'Risoto de queijo',
      'Carne assada com mandioca',
      'Frango ao limão (limão removido)',
      'Peixe ao forno simples',
      'Arroz com lentilha',
      'Bife grelhado simples',
      'Frango empanado',
      'Risoto de palmito',
      'Carne moída com batata',
      'Tilápia simples',
      'Frango com creme de leite',
      'Peixe com manteiga',
      'Bife à milanesa',
      'Risoto cremoso',
      'Carne de sol',
      'Frango com mandioquinha',
      'Peixe grelhado',
      'Arroz com feijão e carne',
      'Frango xadrez (sem pimentão)',
    ],
    'afternoon_snack': [
      'Pipoca caseira simples',
      'Pão de queijo',
      'Banana com mel',
      'Bolo simples',
      'Leite com mel',
      'Biscoitos simples',
      'Tapioca de queijo branco',
      'Iogurte natural',
      'Chips de batata',
      'Bolo de banana',
      'Vitamina de banana',
      'Biscoitos cream cracker',
      'Queijo branco',
      'Pipoca doce',
      'Leite batido',
      'Bolo de fubá',
      'Pão com manteiga',
      'Pera',
      'Vitamina de mamão',
      'Biscoitos de água e sal',
      'Tapioca doce',
      'Iogurte com mel',
      'Bolo caseiro',
      'Leite com aveia',
      'Queijo minas',
      'Pipoca salgada',
      'Mamão',
      'Bolo de coco',
      'Vitamina de coco',
      'Biscoitos de arroz',
    ],
    'dinner': [
      'Sopa de batata com frango',
      'Omelete de queijo',
      'Sanduíche simples de frango',
      'Salada de alface com frango',
      'Wrap de alface com carne',
      'Creme de batata',
      'Omelete simples',
      'Sopa de mandioquinha',
      'Salada simples com ovo',
      'Wrap de alface com frango',
      'Creme de mandioca',
      'Omelete de abobrinha',
      'Sopa de lentilha',
      'Salada de repolho',
      'Wrap de alface com ovo',
      'Creme de chuchu',
      'Omelete de queijo branco',
      'Sopa de frango',
      'Salada de pepino',
      'Wrap simples',
      'Creme de mandioquinha',
      'Omelete de cebola',
      'Sopa de legumes simples',
      'Salada de alface',
      'Wrap de alface com queijo',
      'Creme de batata-doce',
      'Omelete de presunto',
      'Sopa de abobrinha',
      'Salada verde simples',
      'Wrap de alface com presunto',
    ],
    'supper': [
      'Chá de camomila',
      'Leite morno com mel',
      'Banana cozida',
      'Iogurte natural',
      'Gelatina',
      'Castanhas de caju',
      'Leite com aveia',
      'Pera cozida',
      'Queijo cottage',
      'Gelatina diet',
      'Nozes',
      'Leite morno simples',
      'Mamão',
      'Queijo branco',
      'Gelatina de pera',
      'Amêndoas',
      'Leite de coco',
      'Melão',
      'Queijo minas',
      'Gelatina light',
      'Macadâmia',
      'Leite de arroz',
      'Coco fresco',
      'Queijo coalho',
      'Gelatina simples',
      'Castanhas do Pará',
      'Leite com mel',
      'Manga',
      'Queijo brie',
      'Gelatina com coco',
    ],
  },

  // ============= SEM MILHO (180 itens) =============
  'milho': {
    'breakfast': [
      'Pão integral com geleia',
      'Mingau de aveia',
      'Omelete de vegetais',
      'Tapioca de queijo branco',
      'Panqueca de banana',
      'Smoothie de frutas',
      'Crepioca com frango',
      'Pão de queijo (sem amido de milho)',
      'Torrada com abacate',
      'Vitamina de mamão',
      'Omelete simples',
      'Tapioca com presunto',
      'Mingau de quinoa',
      'Panqueca proteica',
      'Smoothie verde',
      'Crepioca com queijo',
      'Pão integral com manteiga',
      'Omelete de brócolis',
      'Tapioca doce',
      'Vitamina de banana',
      'Panqueca de aveia',
      'Mingau de arroz',
      'Crepioca simples',
      'Torrada com queijo',
      'Omelete caprese',
      'Tapioca com atum',
      'Smoothie de morango',
      'Pão com pasta de amendoim',
      'Vitamina de abacate',
      'Panqueca integral',
    ],
    'morning_snack': [
      'Frutas variadas',
      'Mix de castanhas',
      'Iogurte natural',
      'Queijo branco',
      'Vitamina de frutas',
      'Biscoitos de arroz',
      'Maçã com queijo',
      'Nozes',
      'Iogurte grego',
      'Queijo cottage',
      'Smoothie de frutas',
      'Biscoitos de aveia',
      'Pera',
      'Amêndoas',
      'Vitamina de banana',
      'Queijo minas',
      'Banana',
      'Castanhas de caju',
      'Iogurte batido',
      'Queijo brie',
      'Smoothie tropical',
      'Biscoitos integrais',
      'Uvas',
      'Macadâmia',
      'Vitamina de mamão',
      'Queijo prato',
      'Morango',
      'Castanhas do Pará',
      'Iogurte com mel',
      'Queijo coalho',
    ],
    'lunch': [
      'Arroz com feijão e frango',
      'Macarrão à bolonhesa',
      'Bife grelhado com batata',
      'Peixe assado com arroz',
      'Risoto de cogumelos',
      'Carne de panela',
      'Arroz integral com bife',
      'Macarrão ao sugo',
      'Frango xadrez',
      'Salmão com quinoa',
      'Risoto de frango',
      'Estrogonofe (sem amido de milho)',
      'Arroz com lentilha',
      'Macarrão ao pesto',
      'Bife acebolado',
      'Frango assado',
      'Peixe grelhado',
      'Carne moída com legumes',
      'Arroz de forno',
      'Macarrão à carbonara',
      'Frango ao curry',
      'Tilápia grelhada',
      'Risoto de camarão',
      'Carne assada',
      'Arroz com grão-de-bico',
      'Macarrão com brócolis',
      'Frango empanado (farinha de trigo)',
      'Peixe ao molho',
      'Picadinho de carne',
      'Feijoada',
    ],
    'afternoon_snack': [
      'Pipoca de arroz',
      'Pão de queijo (sem amido de milho)',
      'Frutas com mel',
      'Bolo de cenoura',
      'Suco de laranja',
      'Biscoitos de arroz',
      'Tapioca de queijo branco',
      'Iogurte com granola',
      'Chips de batata-doce',
      'Bolo de banana',
      'Vitamina de morango',
      'Biscoitos de aveia',
      'Queijo com geleia',
      'Biscoitos integrais',
      'Smoothie de frutas',
      'Bolo de mandioca',
      'Pão com geleia',
      'Frutas frescas',
      'Vitamina de banana',
      'Biscoitos de polvilho',
      'Tapioca doce',
      'Frutas com iogurte',
      'Bolo caseiro',
      'Smoothie tropical',
      'Queijo branco',
      'Biscoitos de arroz doce',
      'Frutas desidratadas',
      'Bolo de batata-doce',
      'Vitamina de manga',
      'Biscoitos simples',
    ],
    'dinner': [
      'Sopa de legumes',
      'Omelete caprese',
      'Sanduíche de frango',
      'Salada completa',
      'Wrap de alface com carne',
      'Pizza caseira',
      'Sopa de mandioquinha',
      'Omelete de queijo',
      'Sanduíche integral',
      'Salada Caesar',
      'Wrap de alface com frango',
      'Creme de abóbora',
      'Sopa de lentilha',
      'Omelete de brócolis',
      'Sanduíche natural',
      'Salada morna',
      'Wrap de alface simples',
      'Creme de cenoura',
      'Sopa de feijão',
      'Omelete simples',
      'Sanduíche leve',
      'Salada de quinoa',
      'Wrap de alface com ovo',
      'Creme de espinafre',
      'Sopa de batata',
      'Omelete de tomate',
      'Sanduíche de peito de peru',
      'Salada verde',
      'Wrap de alface com atum',
      'Creme de mandioquinha',
    ],
    'supper': [
      'Chá de camomila',
      'Iogurte natural',
      'Frutas cozidas',
      'Leite morno',
      'Gelatina (sem xarope de milho)',
      'Castanhas',
      'Chá de erva-doce',
      'Frutas frescas',
      'Banana assada',
      'Leite com aveia',
      'Gelatina diet',
      'Nozes',
      'Chá de hortelã',
      'Iogurte com mel',
      'Maçã assada',
      'Leite de coco',
      'Gelatina de frutas',
      'Amêndoas',
      'Chá verde',
      'Smoothie leve',
      'Pera cozida',
      'Leite de amêndoas',
      'Gelatina light',
      'Macadâmia',
      'Chá de ervas',
      'Frutas picadas',
      'Banana com canela',
      'Leite simples',
      'Gelatina com frutas',
      'Castanhas de caju',
    ],
  },

  // ============= SEM NÍQUEL (180 itens) =============
  'niquel': {
    'breakfast': [
      'Pão branco com manteiga',
      'Mingau de arroz com leite',
      'Omelete simples',
      'Tapioca com queijo branco',
      'Panqueca de arroz',
      'Vitamina de maçã',
      'Crepioca com frango',
      'Pão de queijo',
      'Torrada com manteiga',
      'Leite com mel',
      'Omelete de queijo',
      'Tapioca com presunto',
      'Mingau de tapioca',
      'Panqueca simples',
      'Vitamina de pera',
      'Crepioca com queijo',
      'Pão branco com geleia',
      'Omelete de tomate',
      'Tapioca doce',
      'Leite com banana',
      'Panqueca de batata',
      'Mingau de polvilho',
      'Crepioca simples',
      'Torrada com geleia',
      'Omelete simples com sal',
      'Tapioca com ovo',
      'Vitamina de melão',
      'Pão com requeijão',
      'Leite com aveia',
      'Panqueca de mandioca',
    ],
    'morning_snack': [
      'Maçã',
      'Pera',
      'Melão',
      'Melancia',
      'Queijo branco',
      'Mamão',
      'Uvas verdes',
      'Queijo cottage',
      'Biscoitos de arroz',
      'Iogurte natural',
      'Coco fresco',
      'Queijo minas',
      'Biscoitos de polvilho',
      'Leite',
      'Manga',
      'Queijo brie',
      'Biscoitos cream cracker',
      'Vitamina de maçã',
      'Abacaxi',
      'Queijo prato',
      'Biscoitos de água e sal',
      'Leite de coco',
      'Carambola',
      'Queijo coalho',
      'Biscoitos simples',
      'Iogurte grego',
      'Lichia',
      'Queijo mussarela',
      'Biscoitos de mandioca',
      'Leite com mel',
    ],
    'lunch': [
      'Arroz branco com frango grelhado',
      'Bife de carne com batata',
      'Peixe branco grelhado com arroz',
      'Risoto de queijo',
      'Carne de panela com mandioca',
      'Arroz com frango desfiado',
      'Frango assado com batatas',
      'Tilápia com legumes',
      'Macarrão com manteiga',
      'Bife acebolado',
      'Frango grelhado com purê',
      'Risoto cremoso',
      'Carne assada com mandioquinha',
      'Frango ao creme',
      'Peixe ao forno',
      'Arroz com carne moída',
      'Bife grelhado simples',
      'Frango empanado',
      'Risoto de palmito',
      'Carne moída com batata',
      'Tilápia simples',
      'Frango com requeijão',
      'Peixe com manteiga',
      'Bife à milanesa',
      'Risoto de frango',
      'Carne de sol',
      'Frango com mandioca',
      'Peixe grelhado simples',
      'Arroz de forno',
      'Frango xadrez simples',
    ],
    'afternoon_snack': [
      'Pipoca de arroz',
      'Pão de queijo',
      'Frutas frescas',
      'Bolo de mandioca',
      'Leite com mel',
      'Biscoitos de arroz',
      'Tapioca de queijo branco',
      'Iogurte natural',
      'Chips de mandioca',
      'Bolo de batata-doce',
      'Vitamina de maçã',
      'Biscoitos de polvilho',
      'Queijo branco',
      'Pipoca simples',
      'Leite batido',
      'Bolo de coco',
      'Pão com manteiga',
      'Pera',
      'Vitamina de pera',
      'Biscoitos cream cracker',
      'Tapioca doce',
      'Iogurte com mel',
      'Bolo caseiro simples',
      'Leite com banana',
      'Queijo minas',
      'Pipoca salgada',
      'Melão',
      'Bolo de arroz',
      'Vitamina de melão',
      'Biscoitos de água e sal',
    ],
    'dinner': [
      'Sopa de batata com frango',
      'Omelete de queijo',
      'Sanduíche simples de frango',
      'Salada de alface com frango',
      'Wrap de alface com carne',
      'Creme de batata',
      'Omelete simples',
      'Sopa de mandioquinha',
      'Salada simples com ovo',
      'Wrap de alface com frango',
      'Creme de mandioca',
      'Omelete de abobrinha',
      'Sopa de arroz com frango',
      'Salada de repolho',
      'Wrap de alface com ovo',
      'Creme de chuchu',
      'Omelete de queijo branco',
      'Sopa de frango',
      'Salada de pepino',
      'Wrap simples',
      'Creme de mandioquinha',
      'Omelete de cebola',
      'Sopa simples',
      'Salada de alface',
      'Wrap de alface com queijo',
      'Creme de batata-doce',
      'Omelete de presunto',
      'Sopa de abobrinha',
      'Salada verde simples',
      'Wrap de alface com presunto',
    ],
    'supper': [
      'Leite morno com mel',
      'Iogurte natural',
      'Maçã cozida',
      'Queijo cottage',
      'Gelatina',
      'Biscoitos de arroz',
      'Leite com banana',
      'Pera cozida',
      'Queijo branco',
      'Gelatina diet',
      'Biscoitos simples',
      'Leite de coco',
      'Melão',
      'Queijo minas',
      'Gelatina de pera',
      'Biscoitos de polvilho',
      'Leite simples',
      'Manga',
      'Queijo coalho',
      'Gelatina light',
      'Biscoitos cream cracker',
      'Leite com mel',
      'Coco fresco',
      'Queijo brie',
      'Gelatina simples',
      'Biscoitos de água e sal',
      'Leite de arroz',
      'Mamão',
      'Queijo prato',
      'Gelatina com coco',
    ],
  },
};

// ============= HELPER FUNCTIONS =============

// Normaliza texto para comparação
function normalizeText(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

// Obtém refeições do pool de intolerância
export function getMealsFromIntolerancePool(
  intoleranceKey: string,
  mealType: string,
  count: number = 5
): string[] {
  const pool = INTOLERANCE_MEAL_POOL[intoleranceKey];
  if (!pool) return [];
  
  const meals = pool[mealType] || [];
  if (meals.length === 0) return [];
  
  // Embaralhar e retornar o número solicitado
  const shuffled = [...meals].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, meals.length));
}

// Obtém uma refeição aleatória do pool de intolerância
export function getRandomMealFromIntolerancePool(intoleranceKey: string, mealType: string): string | null {
  const meals = getMealsFromIntolerancePool(intoleranceKey, mealType, 1);
  return meals.length > 0 ? meals[0] : null;
}

// Verifica se uma refeição está no pool de intolerância
export function isMealInIntolerancePool(intoleranceKey: string, mealType: string, mealName: string): boolean {
  const pool = INTOLERANCE_MEAL_POOL[intoleranceKey];
  if (!pool) return false;
  
  const meals = pool[mealType] || [];
  const normalizedMealName = normalizeText(mealName);
  
  return meals.some(meal => 
    normalizeText(meal).includes(normalizedMealName) || 
    normalizedMealName.includes(normalizeText(meal))
  );
}

// REMOVIDO: getSafeMealSuggestions() foi movido para globalSafetyEngine.ts
// Use: import { getSafeMealSuggestions } from "./globalSafetyEngine.ts"
// Esta função agora está centralizada no Safety Engine para evitar duplicação

// Lista todas as intolerâncias disponíveis no pool
export function getAvailableIntolerances(): string[] {
  return Object.keys(INTOLERANCE_MEAL_POOL);
}

// Verifica se uma intolerância tem pool definido
export function hasIntolerancePool(intoleranceKey: string): boolean {
  return intoleranceKey in INTOLERANCE_MEAL_POOL;
}
