-- Create table for food decomposition mappings
-- This separates processed food decomposition from pure ingredient mappings
CREATE TABLE public.food_decomposition_mappings (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  food_name TEXT NOT NULL,
  base_ingredients TEXT[] NOT NULL DEFAULT '{}',
  is_active BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create unique index on food_name (normalized)
CREATE UNIQUE INDEX idx_food_decomposition_name ON public.food_decomposition_mappings (LOWER(food_name));

-- Enable Row Level Security
ALTER TABLE public.food_decomposition_mappings ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Anyone can view food decomposition mappings" 
ON public.food_decomposition_mappings 
FOR SELECT 
USING (true);

CREATE POLICY "Admins can insert food decomposition mappings" 
ON public.food_decomposition_mappings 
FOR INSERT 
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can update food decomposition mappings" 
ON public.food_decomposition_mappings 
FOR UPDATE 
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can delete food decomposition mappings" 
ON public.food_decomposition_mappings 
FOR DELETE 
USING (has_role(auth.uid(), 'admin'::app_role));

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_food_decomposition_mappings_updated_at
BEFORE UPDATE ON public.food_decomposition_mappings
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert initial data from existing DECOMPOSITION_MAP
INSERT INTO public.food_decomposition_mappings (food_name, base_ingredients, notes) VALUES
('pão', ARRAY['trigo', 'fermento', 'sal'], 'Pão comum de trigo'),
('pão de forma', ARRAY['trigo', 'fermento', 'sal', 'açúcar'], 'Pão de forma industrializado'),
('pão francês', ARRAY['trigo', 'fermento', 'sal'], 'Pão francês tradicional'),
('pão integral', ARRAY['trigo integral', 'fermento', 'sal'], 'Pão integral'),
('pão de queijo', ARRAY['polvilho', 'queijo', 'ovo', 'leite'], 'Pão de queijo mineiro'),
('biscoito', ARRAY['trigo', 'açúcar', 'manteiga'], 'Biscoito comum'),
('biscoito de maisena', ARRAY['trigo', 'maisena', 'açúcar', 'manteiga', 'ovo'], 'Biscoito de maisena'),
('biscoito cream cracker', ARRAY['trigo', 'sal', 'gordura vegetal'], 'Biscoito cream cracker'),
('bolacha', ARRAY['trigo', 'açúcar', 'manteiga'], 'Bolacha comum'),
('bolo', ARRAY['trigo', 'ovo', 'açúcar', 'leite', 'manteiga'], 'Bolo comum'),
('bolo de chocolate', ARRAY['trigo', 'ovo', 'açúcar', 'leite', 'manteiga', 'chocolate', 'cacau'], 'Bolo de chocolate'),
('pizza', ARRAY['trigo', 'fermento', 'queijo', 'tomate', 'azeite'], 'Pizza base'),
('macarrão', ARRAY['trigo', 'ovo'], 'Macarrão comum'),
('massa', ARRAY['trigo', 'ovo'], 'Massa de macarrão'),
('lasanha', ARRAY['trigo', 'ovo', 'queijo', 'leite', 'carne'], 'Lasanha tradicional'),
('coxinha', ARRAY['trigo', 'frango', 'cebola', 'alho'], 'Coxinha de frango'),
('empada', ARRAY['trigo', 'manteiga', 'ovo'], 'Massa de empada'),
('pastel', ARRAY['trigo', 'sal', 'óleo'], 'Massa de pastel'),
('esfiha', ARRAY['trigo', 'fermento', 'carne'], 'Esfiha de carne'),
('torta', ARRAY['trigo', 'ovo', 'manteiga'], 'Torta base'),
('croissant', ARRAY['trigo', 'manteiga', 'fermento', 'leite'], 'Croissant'),
('waffle', ARRAY['trigo', 'ovo', 'leite', 'manteiga', 'açúcar'], 'Waffle'),
('panqueca', ARRAY['trigo', 'ovo', 'leite'], 'Panqueca'),
('crepe', ARRAY['trigo', 'ovo', 'leite'], 'Crepe'),
('sorvete', ARRAY['leite', 'açúcar', 'creme de leite'], 'Sorvete comum'),
('iogurte', ARRAY['leite'], 'Iogurte natural'),
('queijo', ARRAY['leite'], 'Queijo comum'),
('requeijão', ARRAY['leite', 'creme de leite'], 'Requeijão cremoso'),
('cream cheese', ARRAY['leite', 'creme de leite'], 'Cream cheese'),
('manteiga', ARRAY['leite'], 'Manteiga'),
('creme de leite', ARRAY['leite'], 'Creme de leite'),
('leite condensado', ARRAY['leite', 'açúcar'], 'Leite condensado'),
('chocolate', ARRAY['cacau', 'açúcar', 'leite'], 'Chocolate ao leite'),
('chocolate ao leite', ARRAY['cacau', 'açúcar', 'leite'], 'Chocolate ao leite'),
('chocolate branco', ARRAY['manteiga de cacau', 'açúcar', 'leite'], 'Chocolate branco'),
('brigadeiro', ARRAY['leite condensado', 'chocolate', 'manteiga', 'leite'], 'Brigadeiro'),
('pudim', ARRAY['leite', 'ovo', 'açúcar', 'leite condensado'], 'Pudim de leite'),
('mousse', ARRAY['leite', 'creme de leite', 'açúcar'], 'Mousse base'),
('molho branco', ARRAY['leite', 'manteiga', 'trigo'], 'Molho branco/béchamel'),
('molho bechamel', ARRAY['leite', 'manteiga', 'trigo'], 'Molho béchamel'),
('cerveja', ARRAY['cevada', 'lúpulo', 'fermento'], 'Cerveja comum'),
('whisky', ARRAY['cevada', 'malte'], 'Whisky'),
('vodka', ARRAY['trigo', 'batata'], 'Vodka'),
('shoyu', ARRAY['soja', 'trigo', 'sal'], 'Molho de soja'),
('molho de soja', ARRAY['soja', 'trigo', 'sal'], 'Molho de soja'),
('missô', ARRAY['soja', 'arroz', 'sal'], 'Pasta de missô'),
('tofu', ARRAY['soja'], 'Tofu'),
('tempeh', ARRAY['soja'], 'Tempeh'),
('leite de soja', ARRAY['soja'], 'Leite de soja'),
('edamame', ARRAY['soja'], 'Edamame'),
('bacon', ARRAY['porco', 'sal'], 'Bacon'),
('presunto', ARRAY['porco', 'sal'], 'Presunto'),
('salsicha', ARRAY['carne', 'porco', 'sal'], 'Salsicha'),
('linguiça', ARRAY['porco', 'sal', 'páprica'], 'Linguiça'),
('mortadela', ARRAY['carne', 'porco', 'sal'], 'Mortadela'),
('hambúrguer', ARRAY['carne bovina'], 'Hambúrguer de carne'),
('nuggets', ARRAY['frango', 'trigo'], 'Nuggets de frango'),
('empanado', ARRAY['frango', 'trigo', 'ovo'], 'Empanado de frango'),
('ketchup', ARRAY['tomate', 'açúcar', 'vinagre'], 'Ketchup'),
('maionese', ARRAY['ovo', 'óleo', 'vinagre'], 'Maionese'),
('mostarda', ARRAY['semente de mostarda', 'vinagre'], 'Mostarda'),
('molho de tomate', ARRAY['tomate', 'cebola', 'alho', 'azeite'], 'Molho de tomate'),
('catchup', ARRAY['tomate', 'açúcar', 'vinagre'], 'Ketchup'),
('suco de laranja', ARRAY['laranja'], 'Suco de laranja'),
('suco de uva', ARRAY['uva'], 'Suco de uva'),
('café', ARRAY['café'], 'Café'),
('chá', ARRAY['ervas'], 'Chá'),
('achocolatado', ARRAY['cacau', 'açúcar', 'leite'], 'Achocolatado'),
('vitamina', ARRAY['leite', 'fruta'], 'Vitamina de frutas'),
('smoothie', ARRAY['fruta', 'iogurte', 'leite'], 'Smoothie'),
('granola', ARRAY['aveia', 'mel', 'castanhas'], 'Granola'),
('cereal', ARRAY['milho', 'trigo', 'açúcar'], 'Cereal matinal'),
('muesli', ARRAY['aveia', 'frutas secas', 'castanhas'], 'Muesli'),
('tapioca', ARRAY['mandioca'], 'Tapioca'),
('cuscuz', ARRAY['milho', 'sal'], 'Cuscuz de milho'),
('polenta', ARRAY['milho'], 'Polenta'),
('farofa', ARRAY['mandioca', 'manteiga'], 'Farofa'),
('paçoca', ARRAY['amendoim', 'açúcar', 'sal'], 'Paçoca'),
('pé de moleque', ARRAY['amendoim', 'açúcar'], 'Pé de moleque'),
('cocada', ARRAY['coco', 'açúcar'], 'Cocada'),
('beijinho', ARRAY['leite condensado', 'coco', 'manteiga'], 'Beijinho'),
('cajuzinho', ARRAY['amendoim', 'leite condensado', 'chocolate'], 'Cajuzinho'),
('quindim', ARRAY['ovo', 'açúcar', 'coco'], 'Quindim'),
('romeu e julieta', ARRAY['queijo', 'goiabada'], 'Romeu e Julieta'),
('goiabada', ARRAY['goiaba', 'açúcar'], 'Goiabada'),
('doce de leite', ARRAY['leite', 'açúcar'], 'Doce de leite'),
('maria mole', ARRAY['açúcar', 'clara de ovo', 'coco'], 'Maria mole'),
('pão de mel', ARRAY['mel', 'trigo', 'chocolate', 'especiarias'], 'Pão de mel'),
('rabanada', ARRAY['pão', 'leite', 'ovo', 'açúcar', 'canela'], 'Rabanada'),
('french toast', ARRAY['pão', 'leite', 'ovo', 'açúcar', 'canela'], 'French toast/Rabanada'),
('sushi', ARRAY['arroz', 'peixe', 'alga'], 'Sushi'),
('temaki', ARRAY['arroz', 'peixe', 'alga'], 'Temaki'),
('yakisoba', ARRAY['macarrão', 'legumes', 'shoyu', 'carne'], 'Yakisoba'),
('gyoza', ARRAY['trigo', 'carne', 'repolho'], 'Gyoza'),
('ramen', ARRAY['trigo', 'ovo', 'carne', 'shoyu'], 'Ramen'),
('pad thai', ARRAY['macarrão de arroz', 'amendoim', 'ovo', 'camarão'], 'Pad Thai'),
('spring roll', ARRAY['arroz', 'legumes'], 'Rolinho primavera'),
('falafel', ARRAY['grão de bico', 'especiarias'], 'Falafel'),
('hummus', ARRAY['grão de bico', 'tahine', 'limão', 'alho'], 'Hummus'),
('tahine', ARRAY['gergelim'], 'Tahine'),
('babaganoush', ARRAY['berinjela', 'tahine', 'alho'], 'Babaganoush'),
('guacamole', ARRAY['abacate', 'limão', 'cebola', 'tomate'], 'Guacamole'),
('nachos', ARRAY['milho', 'queijo'], 'Nachos'),
('taco', ARRAY['milho', 'carne', 'queijo'], 'Taco'),
('burrito', ARRAY['trigo', 'feijão', 'arroz', 'carne'], 'Burrito'),
('quesadilla', ARRAY['trigo', 'queijo'], 'Quesadilla'),
('enchilada', ARRAY['milho', 'carne', 'queijo', 'molho'], 'Enchilada'),
('risoto', ARRAY['arroz', 'queijo', 'manteiga', 'vinho'], 'Risoto'),
('carbonara', ARRAY['macarrão', 'ovo', 'queijo', 'bacon'], 'Carbonara'),
('bolonhesa', ARRAY['macarrão', 'carne', 'tomate'], 'Bolonhesa'),
('nhoque', ARRAY['batata', 'trigo', 'ovo'], 'Nhoque'),
('ravioli', ARRAY['trigo', 'ovo', 'queijo'], 'Ravioli'),
('cappelletti', ARRAY['trigo', 'ovo', 'carne'], 'Cappelletti'),
('fettuccine', ARRAY['trigo', 'ovo'], 'Fettuccine'),
('penne', ARRAY['trigo'], 'Penne'),
('espaguete', ARRAY['trigo'], 'Espaguete'),
('talharim', ARRAY['trigo', 'ovo'], 'Talharim'),
('strogonoff', ARRAY['carne', 'creme de leite', 'cogumelo'], 'Strogonoff'),
('escondidinho', ARRAY['mandioca', 'carne', 'queijo'], 'Escondidinho'),
('empadão', ARRAY['trigo', 'frango', 'palmito', 'azeitona'], 'Empadão'),
('quiche', ARRAY['trigo', 'ovo', 'leite', 'queijo'], 'Quiche'),
('omelete', ARRAY['ovo'], 'Omelete'),
('fritada', ARRAY['ovo', 'legumes'], 'Fritada'),
('suflê', ARRAY['ovo', 'queijo', 'leite'], 'Suflê'),
('bobó', ARRAY['mandioca', 'camarão', 'leite de coco'], 'Bobó de camarão'),
('vatapá', ARRAY['pão', 'amendoim', 'castanha', 'camarão', 'dendê'], 'Vatapá'),
('acarajé', ARRAY['feijão fradinho', 'dendê', 'camarão'], 'Acarajé'),
('moqueca', ARRAY['peixe', 'leite de coco', 'dendê', 'pimentão'], 'Moqueca'),
('caruru', ARRAY['quiabo', 'camarão', 'dendê'], 'Caruru'),
('feijoada', ARRAY['feijão preto', 'porco', 'linguiça'], 'Feijoada'),
('tutu', ARRAY['feijão', 'farinha de mandioca'], 'Tutu de feijão'),
('tropeiro', ARRAY['feijão', 'farinha de mandioca', 'ovo', 'linguiça'], 'Feijão tropeiro'),
('baião de dois', ARRAY['arroz', 'feijão verde', 'queijo coalho'], 'Baião de dois'),
('galinhada', ARRAY['arroz', 'frango', 'açafrão'], 'Galinhada'),
('arroz carreteiro', ARRAY['arroz', 'carne seca'], 'Arroz carreteiro'),
('canjica', ARRAY['milho branco', 'leite', 'açúcar'], 'Canjica'),
('curau', ARRAY['milho verde', 'leite', 'açúcar'], 'Curau'),
('pamonha', ARRAY['milho verde', 'leite'], 'Pamonha'),
('pato no tucupi', ARRAY['pato', 'tucupi', 'jambu'], 'Pato no tucupi'),
('tacacá', ARRAY['tucupi', 'jambu', 'camarão', 'goma'], 'Tacacá'),
('açaí', ARRAY['açaí'], 'Açaí'),
('cupuaçu', ARRAY['cupuaçu'], 'Cupuaçu'),
('bolo de rolo', ARRAY['trigo', 'açúcar', 'ovo', 'goiabada'], 'Bolo de rolo'),
('cartola', ARRAY['banana', 'queijo coalho', 'açúcar', 'canela'], 'Cartola'),
('carne de sol', ARRAY['carne bovina', 'sal'], 'Carne de sol'),
('charque', ARRAY['carne bovina', 'sal'], 'Charque'),
('jabá', ARRAY['carne bovina', 'sal'], 'Jabá/Charque'),
('churros', ARRAY['trigo', 'açúcar', 'ovo', 'doce de leite'], 'Churros'),
('sonho', ARRAY['trigo', 'fermento', 'ovo', 'creme'], 'Sonho'),
('bomba', ARRAY['trigo', 'ovo', 'manteiga', 'creme'], 'Bomba de chocolate'),
('éclair', ARRAY['trigo', 'ovo', 'manteiga', 'creme', 'chocolate'], 'Éclair'),
('profiterole', ARRAY['trigo', 'ovo', 'manteiga', 'creme'], 'Profiterole'),
('mil folhas', ARRAY['trigo', 'manteiga', 'creme'], 'Mil folhas'),
('palmier', ARRAY['trigo', 'manteiga', 'açúcar'], 'Palmier'),
('strudel', ARRAY['trigo', 'maçã', 'açúcar', 'canela'], 'Strudel'),
('cheesecake', ARRAY['cream cheese', 'açúcar', 'ovo', 'biscoito'], 'Cheesecake'),
('tiramisu', ARRAY['mascarpone', 'café', 'ovo', 'biscoito', 'cacau'], 'Tiramisu'),
('panna cotta', ARRAY['creme de leite', 'açúcar', 'gelatina'], 'Panna cotta'),
('cannoli', ARRAY['trigo', 'ricota', 'açúcar', 'chocolate'], 'Cannoli'),
('gelato', ARRAY['leite', 'açúcar', 'ovo'], 'Gelato'),
('parfait', ARRAY['iogurte', 'granola', 'frutas'], 'Parfait'),
('crème brûlée', ARRAY['creme de leite', 'ovo', 'açúcar', 'baunilha'], 'Crème brûlée'),
('flan', ARRAY['leite', 'ovo', 'açúcar'], 'Flan'),
('charlotte', ARRAY['biscoito', 'creme', 'frutas'], 'Charlotte'),
('trifle', ARRAY['bolo', 'creme', 'frutas'], 'Trifle'),
('brownie', ARRAY['chocolate', 'manteiga', 'açúcar', 'ovo', 'trigo'], 'Brownie'),
('cookie', ARRAY['trigo', 'manteiga', 'açúcar', 'ovo', 'chocolate'], 'Cookie'),
('muffin', ARRAY['trigo', 'ovo', 'açúcar', 'manteiga'], 'Muffin'),
('cupcake', ARRAY['trigo', 'ovo', 'açúcar', 'manteiga'], 'Cupcake'),
('macaron', ARRAY['amêndoa', 'açúcar', 'clara de ovo'], 'Macaron'),
('merengue', ARRAY['clara de ovo', 'açúcar'], 'Merengue'),
('suspiro', ARRAY['clara de ovo', 'açúcar'], 'Suspiro'),
('pavlova', ARRAY['clara de ovo', 'açúcar', 'creme', 'frutas'], 'Pavlova'),
('shortcake', ARRAY['trigo', 'manteiga', 'açúcar', 'creme', 'morango'], 'Shortcake'),
('pound cake', ARRAY['trigo', 'manteiga', 'açúcar', 'ovo'], 'Pound cake'),
('banana bread', ARRAY['banana', 'trigo', 'açúcar', 'ovo'], 'Banana bread'),
('carrot cake', ARRAY['cenoura', 'trigo', 'açúcar', 'ovo', 'nozes'], 'Carrot cake'),
('red velvet', ARRAY['trigo', 'cacau', 'ovo', 'cream cheese'], 'Red velvet'),
('molho pesto', ARRAY['manjericão', 'parmesão', 'alho', 'azeite', 'castanha'], 'Molho pesto'),
('molho alfredo', ARRAY['manteiga', 'parmesão', 'creme de leite'], 'Molho alfredo'),
('molho rosé', ARRAY['tomate', 'creme de leite'], 'Molho rosé'),
('molho madeira', ARRAY['vinho madeira', 'creme de leite', 'cogumelo'], 'Molho madeira'),
('molho gorgonzola', ARRAY['gorgonzola', 'creme de leite'], 'Molho gorgonzola'),
('molho quatro queijos', ARRAY['queijo', 'creme de leite'], 'Molho quatro queijos'),
('vinagrete', ARRAY['tomate', 'cebola', 'pimentão', 'vinagre'], 'Vinagrete'),
('chimichurri', ARRAY['salsa', 'alho', 'orégano', 'vinagre', 'azeite'], 'Chimichurri'),
('aioli', ARRAY['alho', 'ovo', 'azeite'], 'Aioli'),
('tartar', ARRAY['maionese', 'pepino', 'alcaparra'], 'Molho tártaro'),
('barbecue', ARRAY['tomate', 'açúcar', 'vinagre', 'especiarias'], 'Molho barbecue'),
('teriyaki', ARRAY['shoyu', 'açúcar', 'mirin', 'gengibre'], 'Molho teriyaki'),
('agridoce', ARRAY['açúcar', 'vinagre', 'tomate'], 'Molho agridoce'),
('curry', ARRAY['especiarias', 'leite de coco'], 'Curry'),
('massaman', ARRAY['especiarias', 'leite de coco', 'amendoim'], 'Massaman'),
('tikka masala', ARRAY['tomate', 'creme', 'especiarias'], 'Tikka masala'),
('biryani', ARRAY['arroz', 'especiarias', 'carne'], 'Biryani'),
('samosa', ARRAY['trigo', 'batata', 'ervilha', 'especiarias'], 'Samosa'),
('naan', ARRAY['trigo', 'iogurte', 'fermento'], 'Naan'),
('chapati', ARRAY['trigo integral'], 'Chapati'),
('papadum', ARRAY['lentilha'], 'Papadum'),
('dosa', ARRAY['arroz', 'lentilha'], 'Dosa'),
('idli', ARRAY['arroz', 'lentilha'], 'Idli'),
('pakora', ARRAY['grão de bico', 'legumes'], 'Pakora'),
('bhaji', ARRAY['cebola', 'grão de bico', 'especiarias'], 'Bhaji'),
('paneer', ARRAY['leite'], 'Paneer'),
('raita', ARRAY['iogurte', 'pepino', 'especiarias'], 'Raita'),
('chutney', ARRAY['frutas', 'especiarias', 'açúcar'], 'Chutney'),
('dal', ARRAY['lentilha', 'especiarias'], 'Dal'),
('palak', ARRAY['espinafre', 'especiarias'], 'Palak'),
('korma', ARRAY['creme', 'castanha', 'especiarias'], 'Korma'),
('vindaloo', ARRAY['carne', 'vinagre', 'especiarias'], 'Vindaloo'),
('tandoori', ARRAY['iogurte', 'especiarias'], 'Tandoori'),
('kebab', ARRAY['carne', 'especiarias'], 'Kebab'),
('shawarma', ARRAY['carne', 'pão pita', 'especiarias'], 'Shawarma'),
('fajita', ARRAY['carne', 'pimentão', 'cebola', 'tortilha'], 'Fajita'),
('chimichanga', ARRAY['tortilha', 'carne', 'feijão', 'queijo'], 'Chimichanga'),
('tamale', ARRAY['milho', 'carne', 'especiarias'], 'Tamale'),
('pupusa', ARRAY['milho', 'queijo', 'feijão'], 'Pupusa'),
('arepa', ARRAY['milho'], 'Arepa'),
('empanada', ARRAY['trigo', 'carne'], 'Empanada'),
('ceviche', ARRAY['peixe', 'limão', 'cebola'], 'Ceviche'),
('poke', ARRAY['peixe', 'arroz', 'alga'], 'Poke'),
('carpaccio', ARRAY['carne crua', 'azeite', 'limão'], 'Carpaccio'),
('tartare', ARRAY['carne crua', 'alcaparra', 'cebola'], 'Tartare'),
('bruschetta', ARRAY['pão', 'tomate', 'azeite', 'alho'], 'Bruschetta'),
('crostini', ARRAY['pão', 'azeite'], 'Crostini'),
('focaccia', ARRAY['trigo', 'azeite', 'fermento'], 'Focaccia'),
('ciabatta', ARRAY['trigo', 'fermento', 'azeite'], 'Ciabatta'),
('baguete', ARRAY['trigo', 'fermento', 'sal'], 'Baguete'),
('brioche', ARRAY['trigo', 'manteiga', 'ovo', 'açúcar'], 'Brioche'),
('challah', ARRAY['trigo', 'ovo', 'mel'], 'Challah'),
('pretzel', ARRAY['trigo', 'fermento', 'sal'], 'Pretzel'),
('bagel', ARRAY['trigo', 'fermento'], 'Bagel'),
('donut', ARRAY['trigo', 'açúcar', 'ovo', 'leite'], 'Donut'),
('rosquinha', ARRAY['trigo', 'açúcar', 'ovo'], 'Rosquinha'),
('churro', ARRAY['trigo', 'açúcar', 'óleo'], 'Churro'),
('buñuelo', ARRAY['trigo', 'ovo', 'açúcar'], 'Buñuelo'),
('sopapilla', ARRAY['trigo', 'fermento', 'mel'], 'Sopapilla'),
('malasada', ARRAY['trigo', 'ovo', 'açúcar', 'leite'], 'Malasada'),
('beignet', ARRAY['trigo', 'ovo', 'leite', 'açúcar'], 'Beignet'),
('zeppole', ARRAY['trigo', 'ovo', 'ricota'], 'Zeppole'),
('sfogliatella', ARRAY['trigo', 'ricota', 'laranja'], 'Sfogliatella'),
('torrone', ARRAY['amêndoa', 'mel', 'clara de ovo'], 'Torrone'),
('nougat', ARRAY['amêndoa', 'mel', 'clara de ovo'], 'Nougat'),
('praline', ARRAY['amêndoa', 'açúcar'], 'Praline'),
('trufa', ARRAY['chocolate', 'creme de leite'], 'Trufa'),
('ganache', ARRAY['chocolate', 'creme de leite'], 'Ganache'),
('fondant', ARRAY['açúcar', 'glucose'], 'Fondant'),
('marzipan', ARRAY['amêndoa', 'açúcar'], 'Marzipan'),
('glacê', ARRAY['açúcar', 'clara de ovo'], 'Glacê'),
('buttercream', ARRAY['manteiga', 'açúcar'], 'Buttercream'),
('chantilly', ARRAY['creme de leite', 'açúcar'], 'Chantilly'),
('creme confeiteiro', ARRAY['leite', 'ovo', 'açúcar', 'amido'], 'Creme confeiteiro'),
('creme inglês', ARRAY['leite', 'ovo', 'açúcar', 'baunilha'], 'Creme inglês'),
('sabayon', ARRAY['ovo', 'açúcar', 'vinho'], 'Sabayon'),
('zabaglione', ARRAY['ovo', 'açúcar', 'marsala'], 'Zabaglione');

COMMENT ON TABLE public.food_decomposition_mappings IS 'Mapeamento de alimentos processados para seus ingredientes base. Usado para validação de segurança alimentar quando o usuário informa ter consumido um alimento processado.';